### ISSUE TITLE
VipsProcessor

### ISSUE THREAD

**Issue by adolski** [cantaloupe-project/cantaloupe#2]
The vips command-line tool does not support operation-chaining, making it not very useful. A JNI interface to the Vips API would enable a potentially very fast VipsProcessor.

**Comment by jpstroop** [comment]
Do you mean because it can't read from STDIN? I've run into this before (Kakadu has the same problem) and used named pipes (i.e. `mkfifo`) to get around it. [Example](https://github.com/loris-imageserver/loris/blob/development/misc/jp2_kakadu_pillow.py#L23-L44).

**Comment by adolski** [comment]
Thanks, @jpstroop . According to [the vips wiki](http://www.vips.ecs.soton.ac.uk/index.php?title=Libvips#Command-line_interface), the command-line tool is only able to perform one operation at a time. So, apparently, a chain of vips processes would be needed using FIFOs as communication.

**Comment by jpstroop** [comment]
Ahh, cool. Much better than a chain of FIFOs...what could go wrong! ;-)
