### ISSUE TITLE
How can I reuse TIFF metadata (EXIF, IPTC, XMP)?

### ISSUE THREAD

**Issue by giancarlobi** [cantaloupe-project/cantaloupe#269]
I'd like to manage json info response of a TIFF source image merging metadata from TIFF image embed ExIF/IPTC/XMP into info.json response.
Have I to use delegate? i.e. delegate script reads metadata and then alters info.json.
Sorry if this is a really strange question.
Best
Giancarlo

**Comment by adolski** [comment]
Hi @giancarlobi ,

Could you explain your use case?

**Comment by giancarlobi** [comment]
Hi @adolski , thanks in advanced,
We use Cantaloupe in an architecture for digital preservation and presentation. We have images (postalcards, maps, pages of book) with some related metadata (Dublin Core style but not only).
My idea is to store metadata into TIFF (using TIFF metadata, only one file) so Cantaloupe will be the point of access between front-end site and object storage (of any type).
I'd like to have that TIFF metadata included into info.json response returned by Cantaloupe, I know json allows add more key-value pair to it.
I don't know if it is possible because it is not clear for me how Cantaloupe creates info.json.
Thanks again
PS. 4.0.3 works like a charm !!!

**Comment by adolski** [comment]
Ahhh, I get it. I haven't really considered this use case, but it's interesting.

One possible strategy would be to use a tool like exiv2 or exiftool to get this info and return it from the `extra_iiif2_information_response_keys()` delegate method.

I'm working on a major overhaul of the way metadata is handled internally which will hopefully make it into the version after 4.1. The idea is that metadata would be read at the time an image is first accessed, and stored in the internal `Info` objects that get used all over the place internally. I don't know yet if that's going to work, but if it does then it would be easy to expose the `Info` object to `extra_iiif2_information_response_keys()` so that you wouldn't have to read the metadata manually.

Does this make sense?

**Comment by giancarlobi** [comment]
Make a lot of sense, @adolski !!!
For at least two reasons: not to read manually and caching !!!
Cantaloupe is today a fundamental brick of digital repository architecture, adding metadata features convert it in the main node to share digital objects between institutions.
Thanks !!!

**Comment by regisrob** [comment]
Bumping into this thread... this is an interesting use case. But how would you represent the metadata in the info.json response? What kind of metadata do you expect to be embedded in it?

On the metadata side, Image API 2.1 only has `attribution`, `license` and `logo` properties, and the ability to provide a hook to an external `service` (which could be a link to a web service providing additional metadata about the image for instance).
Image API 3.0-beta has the same kind of rights related properties (`requiredStatement`, `rights`, `logo`), and introduces new linking properties in addition to `service`: `partOf` and `seeAlso`.

Are the metadata elements that come with the TIFF supposed to be displayed by other IIIF viewers? If the answer is yes, and depending on the need you are trying to fullfill regarding those metadata, I wonder whether it would not be the job of the Presentation API to handle that... (maybe not)

**Comment by giancarlobi** [comment]
@regisrob thanks for your notes. 
The answer is no, the TIFF metadata passed by Cantaloupe info.json are managed with a custom module that is able to extract metadata and present it to the final user.
We are thinking about a single file to store OBJECT+METADATA retrieved by Cantaloupe to our application. Cantaloupe is great to manage several type of storage and it has a good cache and its performance are very high.
The @adolski idea is ok also for a standard info.json (caching is very important) and in addition allows a custom info.json to be generated.
