### ISSUE TITLE
Empty image regions at certain scales when using KakaduNativeProcessor with certain tiled images

### ISSUE THREAD

**Issue by bonaventure** [cantaloupe-project/cantaloupe#275]
After uploading 30,000+ tiled JP2 images without issue, we are suddenly experiencing issues with some of them. At first glance the images appear to be missing data (entire sections of the image are blank), but if you zoom in on the image it shows the higher resolution tiles. The thumbnails also work just fine. I'm not sure how to correct the problem. We tried reprocessing the image and get the same result. 
Here is an example:
https://iiif.newmanstudies.org/iiif/2/B3%2FB050%2FA003%2FNewman_B050_A003_D010_P001.jp2/full/full/0/default.jpg

Look at the same image constrained to 2000 pixels and everything works:
https://iiif.newmanstudies.org/iiif/2/B3%2FB050%2FA003%2FNewman_B050_A003_D010_P001.jp2/full/2000,/0/default.jpg

If I go back down to 1500 it breaks again. 
https://iiif.newmanstudies.org/iiif/2/B3%2FB050%2FA003%2FNewman_B050_A003_D010_P001.jp2/full/1500,/0/default.jpg

Going up to 1600 work again.

The JSON for this file is here: https://iiif.newmanstudies.org/iiif/2/B3%2FB050%2FA003%2FNewman_B050_A003_D010_P001.jp2/info.json

The original tifs are not tiled and the images are complete, so it seems to be something with the tiles in the JP2 that are not working. I'm not sure where to look to solve the problem.

**Comment by adolski** [comment]
Hi @bonaventure ,

What processor are you using? Could you post the JP2 image somewhere where I can download it?

**Comment by bonaventure** [comment]
We are using the kakadu processor. And here is the image:
https://drive.google.com/file/d/15S12xLnJHM9DHps7pqkby2HLDi4_3YVZ/view?usp=sharing

**Comment by adolski** [comment]
Thanks, I've downloaded it and will check it out.

**Comment by adolski** [comment]
I believe this is likely to be a bug in Kakadu, either in `kdu_region_decompressor` (which is the class that KakaduNativeProcessor uses for decoding) or on the encoding side. It's also possible that I'm using `kdu_region_decompressor` incorrectly, but less likely, given that the behavior occurs only within narrow scale ranges.

I will need to distill this down into an SSCCE and send a bug report.

**Comment by Necklaces** [comment]
Hi, we were also affected by this bug just now. Here's an image that works for 20% of original image size but not for 10% of original image size. Using kdu_render to scale the same image works, however.

[1235955.jp2.zip](https://github.com/cantaloupe-project/cantaloupe/files/3377303/1235955.jp2.zip)

**Comment by ebenenglish** [comment]
We are also seeing this issue (blank tiles at lower resolution) on certain images with `KakaduNativeProcessor`. Here are two example images:
 - https://fedora.digitalcommonwealth.org/fedora/objects/commonwealth:kk91fq38b/datastreams/accessMaster/content
 - https://fedora.digitalcommonwealth.org/fedora/objects/commonwealth:q524n560k/datastreams/accessMaster/content

The missing image regions are also blank when rendering a full-size JPEG, e.g. `/full/full/0/default.jpg`.

**Comment by adolski** [comment]
This turned out not to be a bug in Kakadu. It should be fixed now.

As a bonus, the fix has a side effect of making transfer of decompressed pixels into the raster more efficient, and overall response times from KNP seem to be about 10% faster now.

I believe the image shared by @Necklaces is suffering from a different issue (even though the symptoms are the same) and I've opened #309 to track that.
