### ISSUE TITLE
HTTPS Set-Up- not working

### ISSUE THREAD

**Issue by rentonsa** [cantaloupe-project/cantaloupe#286]
Hi folks

Wondered if you could advise me. Cantaloupe works fine for me http on 8182, but I need to change it to https for various reasons.

I have done the following to set up https:

- Opened port 8183
- Set up a virtualhost (see bottom of issue)
- Set up a keystore (password redacted below, but it is the right one!)
- Changed cantaloupe.properties to below.

Browser error is 
Not Found

The requested URL /iiif/2/Wuerzburg_submission1_tyrannicide.jpg/info.json was not found on this server.

and the apache error log says

[Mon May 13 13:23:09.593919 2019] [proxy_http:error] [pid 53048] (70014)End of file found: [client 129.215.240.51:53113] AH01102: error reading status line from remote server lac-php-test2.is.ed.ac.uk:8183
[Mon May 13 13:23:09.593989 2019] [proxy:error] [pid 53048] [client 129.215.240.51:53113] AH00898: Error reading from remote server returned by /iiif/2/Wuerzburg_submission1_tyrannicide.jpg/info.json

Anything obvious I'm missing?

Cheers
Scott

cantaloupe.properties extract:

# !! Whether to enable HTTPS access (https://), and on what host interface
# and TCP port. (Applies in standalone mode only.)
https.enabled = true
https.host = 0.0.0.0
https.port = 8183
# !! Available values are `JKS` and `PKCS12`. (Standalone mode only.)
https.key_store_type = JKS
https.key_store_password = xxxxxxx
https.key_store_path = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre/bin/KeyStore.jks
https.key_password = xxxxxxxx

Virtual Host:

<VirtualHost *:80>
  # X-Forwarded-Host will be set automatically by the web server.
  RequestHeader set X-Forwarded-Proto HTTP
  RequestHeader set X-Forwarded-Port 80
  RequestHeader set X-Forwarded-Path /

  ServerName test.cantaloupe.is.ed.ac.uk
  AllowEncodedSlashes NoDecode
  ProxyPassReverseCookiePath / /
  ErrorLog logs/image-error.log
  CustomLog logs/image-access.log combined

  ProxyPass / http://lac-php-test2.is.ed.ac.uk:8183/ nocanon retry=1 acquire=3000 timeout=600 Keepalive=On
  ProxyPassReverse / http://lac-php-test2.is.ed.ac.uk:8183/
  ProxyPassReverseCookieDomain lac-php-test2.is.ed.ac.uk:8183 test.cantaloupe.is.ed.ac.uk
  ProxyPreserveHost on
</VirtualHost>

**Comment by adolski** [comment]
Hi @rentonsa,

Can you access cantaloupe directly via HTTPS on port 8183 without going through Apache?

Are you sure your reverse proxy is configured correctly? It looks like you are trying to proxy public HTTP to private HTTPS?

**Comment by rentonsa** [comment]
Thanks for the response. I think our setup has become unnecessarily convoluted partly because of other things running on that server. I've been advised to do the https through an external load balancer, pointing at http on the server. I'm hoping that will work- if not I'll get back in touch (so won't close the issue just yet).
