### ISSUE TITLE
Access to AWS S3 using aws iam instance profile?

### ISSUE THREAD

**Issue by Puththiran** [cantaloupe-project/cantaloupe#288]
Does the version 4.1.1 support aws iam instance profile so that no need to specify S3Source.access_key_id and S3Source.secret_key? if yes can you provide the some guide?
if not is there a plan to include in the future release?

**Comment by adolski** [comment]
Yes, see here: https://cantaloupe-project.github.io/manual/4.1/sources.html#S3Source
