### ISSUE TITLE
Server 4.1.2 stops retrieving tiles/answer after some minutes

### ISSUE THREAD

**Issue by giancarlobi** [cantaloupe-project/cantaloupe#289]
@adolski I observed this strange issue after updating to 4.1.2 from 4.1, while update to 4.1.1 is ok.
When 4.1.2 starts all works good but after some minutes (maybe 15m) stops to answer to client and no error/log appears into log (debug level set). I saw that TCP connections between client and server are opened but no one between server and http tile source origin.
I observed that jetty version is the same for 4.1 and 4.1.1 but not for 4.1.2.
Finally, in syslog whet 4.1.2 starts, this line is logged if can be helpful:
`WARN:oejusS.config:qtp1761061602-54: Weak cipher suite TLS_RSA_WITH_AES_128_GCM_SHA256 enabled for SslContextFactory@57cd8c09[provider=null,keyStore=null,trustStore=null]`

**Comment by adolski** [comment]
Hi @giancarlobi , thanks for reporting this. Are you saying you suspect an issue in the Jetty client used by HttpSource?

Are you able to downgrade your Jetty to the previous version (9.4.12.v20180830) to confirm whether that fixes it?

**Comment by giancarlobi** [comment]
> Hi @giancarlobi , thanks for reporting this. Are you saying you suspect an issue in the Jetty client used by HttpSource?
> 
Yes, I do
> Are you able to downgrade your Jetty to the previous version (9.4.12.v20180830) to confirm whether that fixes it?

Do you mean, 4.1.2 changing pom.xml and compiling it ?

**Comment by adolski** [comment]
> > Are you able to downgrade your Jetty to the previous version (9.4.12.v20180830) to confirm whether that fixes it?
> 
> Do you mean, 4.1.2 changing pom.xml and compiling it ?

Yes; I think it should be a drop-in replacement. If that version works (I suspect it will) then I will probably revert back to it for 4.1.3.

**Comment by giancarlobi** [comment]
@adolski ok, I'll do it tomorrow , here we are at the end of the day.

**Comment by giancarlobi** [comment]
> Are you able to downgrade your Jetty to the previous version (9.4.12.v20180830) to confirm whether that fixes it?

@adolski I downgraded Jetty and 4.1.2 issue is fixed so definitely it depends on Jetty version.

**Comment by adolski** [comment]
Thanks for confirming, @giancarlo.

I bet you're getting tired of these Jetty bugs by now. 😄 

I will revert the Jetty version for 4.1.3. Also, I'm considering using a different HTTP client in 5.0.

**Comment by giancarlobi** [comment]
No probl @adolski , thanks to you for your great job with Cantaloupe.
I'm happy to give my very very small contribute to this great project.
