### ISSUE TITLE
Findbug build failure and dead link

### ISSUE THREAD

**Issue by eric-gagnon** [cantaloupe-project/cantaloupe#291]
Hello!

I'm taking a university class and we had to complete assignments using open source software.

I took the opportunity to dig further in Cantaloupe mostly by curiosity as I'm not involved in the maintenance of the installation that we have in the context of my work.

First assignment was doing UML reverse engineering  to get a better understanding of the conception of a software and the one we are working on currently is more on quality evaluation (but again in relation to software conception) (ex. page 16 of http://www.cqaa.org/resources/Documents/Presentations%202018/Trissential_SQS_CQAA_Presentation%20Final.pdf)

So while exploring I had an error while using the documented command
mvn clean compile findbugs:findbugs findbugs:gui

Is this the expected behavior or an idea of what I should be looking at? Google is not helping much on that one. I'm using Java 1.9.

```
[INFO] --- findbugs-maven-plugin:3.0.1:findbugs (default-cli) @ cantaloupe ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/C:/Users/eric/.m2/repository/org/codehaus/groovy/groovy-all/2.4.0/groovy-all-2.4.0.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

I have also noticed this deadlink :  https://github.com/cantaloupe-project/output-tester

Cantaloupe is **very** high quality (documentation, sources, etc.) so far and it's actually make the assignment event more difficult! 

We had to find "outliers" on the quality side (maintenance, security, etc.) using automated tools (SonarQube, Jarchitect, even tried some more exotic tools like Codecity and iplasma) and more manual checks. Found a few things to nit pick on maintenance side (ex. java2d processor cyclomatic complexity by exemple, wich comme second or third after the generated protobuf file) but it's more difficult to find other problems on performance and security side as we have to be cautious with measures with undocumented / unknown boundaries (specifications).

I have run the integrated owasp test by exemple and noticed the advisories for a few dependencies but I'm missing information of what kind of security Cantaloupe was really aiming for (ex. should the dashboard be using something else than auth basic? But I understand that a sane admin would not expose that part of Cantaloupe outside!).

I was able to find a few accessibility issues (using 3 differents chrome extension, manual assessment / screen reader to be completed) in the dashboard, it's really minor but I was wondering, is Cantaloupe falling under the general accessibility rule of the University? http://disability.illinois.edu/academic-support/accessible-it-group/web_accessibility
Would it make sense to report it as an usability defect? I would probably dismiss that but then again I'm really working hard to find a quality aspect that is really problematic.

Thanks and hats off for the great work.

Eric

**Comment by eric-gagnon** [comment]
Cantaloupe view in "codecity" (https://wettel.github.io/codecity.html)
![codecity_3](https://user-images.githubusercontent.com/21067311/59079236-c4452c00-88b0-11e9-98ee-90303f9647b0.png)
![codecity](https://user-images.githubusercontent.com/21067311/59079238-c60eef80-88b0-11e9-9af8-cc7a8e169d40.png)

**Comment by adolski** [comment]
Hi @eric-gagnon,

Thanks for reporting in on your findings. I'm surprised that Cantaloupe did so well. I know for a fact that it does have a lot of problems, but the analysis tools probably aren't seeing things like functionality gaps and other "higher level" things, and bugs in dependencies.

Re: Findbugs -- I guess it hasn't been updated for Java 9. If you have 8 installed, you should be able to run it on the `release/4.1` branch (`develop` now requires 11+). It will report a lot of problems, but almost all of them are in the `kdu_jni` package.

And the [output tester](https://github.com/cantaloupe-project/output-tester) needs more work and I shouldn't have added it to the readme yet. :)

Interesting view of "Cantaloupolis" there -- I had no idea kdu_jni would be so "big." I guess it's the entire Kakadu API, but still.
