### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [cantaloupe-project/cantaloupe#295]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/edu/illinois/library/cantaloupe/operation/OperationList.java: Line number => 571: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/edu/illinois/library/cantaloupe/cache/FilesystemCache.java: Line number => 325: API name => MessageDigest:<BR> File name => src/main/java/edu/illinois/library/cantaloupe/script/ScriptWatcher.java: Line number => 57: API name => MessageDigest:<BR> File name => src/main/java/edu/illinois/library/cantaloupe/util/StringUtils.java: Line number => 64: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/edu/illinois/library/cantaloupe/util/StringUtils.java: Line number => 66: API name => MessageDigest:<BR> File name => src/main/java/edu/illinois/library/cantaloupe/operation/overlay/StringOverlay.java: Line number => 197: API name => MessageDigest:<BR> File name => src/main/java/edu/illinois/library/cantaloupe/operation/overlay/StringOverlay.java: Line number => 195: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/edu/illinois/library/cantaloupe/script/ScriptWatcher.java: Line number => 55: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/edu/illinois/library/cantaloupe/operation/OperationList.java: Line number => 573: API name => MessageDigest:<BR> File name => src/main/java/edu/illinois/library/cantaloupe/cache/FilesystemCache.java: Line number => 323: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/edu/illinois/library/cantaloupe/config/HeritablePropertiesConfiguration.java: Line number => 433: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/edu/illinois/library/cantaloupe/config/HeritablePropertiesConfiguration.java: Line number => 434: API name => MessageDigest:<BR> File name => src/main/java/edu/illinois/library/cantaloupe/config/HeritablePropertiesConfiguration.java: Line number => 434: API name => MessageDigest:<BR>

**Comment by adolski** [comment]
https://docs.oracle.com/javase/8/docs/api/java/security/MessageDigest.html

> Every implementation of the Java platform is required to support the following standard MessageDigest algorithms:
>
>MD5
>SHA-1
>SHA-256
