### ISSUE TITLE
Support Unicode syntax for the response-content-disposition filename argument

### ISSUE THREAD

**Issue by adolski** [cantaloupe-project/cantaloupe#302]
See https://github.com/cantaloupe-project/cantaloupe/commit/7c27127985bf38f852abb5bab76786aa03e511fd#r34536993

**Comment by acdha** [comment]
I noticed two other minor issues – want me to ticket them separately?

* RedBot flagged the `Link:` header as invalid — and it looks like while [RFC 5988](https://tools.ietf.org/html/rfc5988#section-5) does not specify whitespace between the URI and the semicolon for the link parameter, [RFC 8288](https://tools.ietf.org/html/rfc8288#section-3) does — i.e. the second one is more proper:

```
Link: <https://chroniclingamerica.loc.gov/iiif/2/ncu_chestnut_ver01%2Fdata%2Fsn91068765%2F00415667371%2F1919080801%2F0239.jp2/0,0,6235,9100/full/0/default.jpg>;rel="canonical"
```

```
Link: <https://chroniclingamerica.loc.gov/iiif/2/ncu_chestnut_ver01%2Fdata%2Fsn91068765%2F00415667371%2F1919080801%2F0239.jp2/0,0,6235,9100/full/0/default.jpg>; rel="canonical"
```

* I noticed that spaces are stripped from filenames — for example, https://chroniclingamerica.loc.gov/lccn/sn91068765/1919-08-08/ed-1/seq-1/print/image_559x817_from_0%2C0_to_6235%2C9100/ links to https://chroniclingamerica.loc.gov/iiif/2/ncu_chestnut_ver01%2Fdata%2Fsn91068765%2F00415667371%2F1919080801%2F0239.jp2/0,0,6235,9100/full/0/default.jpg?response-content-disposition=attachment%3B%20filename%3D%22sn91068765%201919-08-08%201%201%20image%20559x817%20from%200x0%20to%206235x9100.jpg%22 which has `%20` in the filename but the resulting header has them stripped: `Content-Disposition: attachment; filename=sn910687651919-08-0811image559x817from0x0to6235x9100.jpg`

**Comment by adolski** [comment]
Please do, thanks!
