### ISSUE TITLE
HTTP API/health always red,  kdu_jni.KduException at latest (sucessfully) processed image

### ISSUE THREAD

**Issue by ghohmann** [cantaloupe-project/cantaloupe#307]
Hi,
I'm using the latest cantaloupe 4.1.3 standalone on ubuntu 18.04.3 LTS for jp2 processing.
Everything works fine, but I encountered a strange behaviour of the HTTP API.

Calling http://localhost:8182/health the returned status is always "color: red" with following message:

`"message": "kdu_jni.KduException (1990-1069_20061122_001 -> FilesystemSource -> KakaduNativeProcessor)"`

"1990-1069_20061122_001" is a typical image identifier in our system. Despite the error message the image can be retrieved normally without any entry in the canataloupe error log. What makes it even more strange is that the "health" always shows the given error message for the _last processed image_. So when i call image "abcd" successfully, the health status says "red" and "kdu_jni.KduException (abcd -> FilesystemSource -> KakaduNativeProcessor)". And when I call "efgh" afterwards, it shows "kdu_jni.KduException (efgh-> FilesystemSource -> KakaduNativeProcessor)".

**Comment by adolski** [comment]
Thanks for reporting this, @ghohmann . It looks like this feature has been broken throughout the 4.1 series but the tests weren't complete enough to pick it up. The above commit ought to fix it. Please reopen if you find otherwise.
