### ISSUE TITLE
Timeout issue loading images for other APIs

### ISSUE THREAD

**Issue by jamesw-cogapp** [cantaloupe-project/cantaloupe#311]
Hello,

I'm having issues using Google Vision with a cantaloupe server. It works fine with lower resolution images but with higher resolution ones it appears that the images are not loading fast enough on the server. Is there a way around this?

The server has 2G CPU and 4G memory dedicated to it.

Thanks.

**Comment by adolski** [comment]
Hi,

Where are your images hosted (i.e. what Source are you using)? What format(s) are they and what kinds of images are you trying to retrieve from the image server (thumbnail sized, tile sized, larger?) [This](https://cantaloupe-project.github.io/manual/4.1/images.html) may help if you haven't seen it yet.

**Comment by jamesw-cogapp** [comment]
Hello,

They are hosted on AWS in an S3 bucket.

They are in PTIF format and we are retrieving high resolution jpegs. ~ 3000 px wide.

Thanks.

**Comment by adolski** [comment]
It's normal for response times to slow down roughly in proportion to output dimensions. Comparing a 3000x3000 image to a 500x500 image (for example), there are 36x more pixels to JPEG-compress and there's no way around that.

A couple of ways to compensate are to employ a faster CPU, or to make multiple requests for smaller tiles, which can be handled by multiple threads/cores.

(This might also be related to #296.)
