### ISSUE TITLE
Handle empty request headers

### ISSUE THREAD

**Issue by RRMoelker** [cantaloupe-project/cantaloupe#312]
Currently a request header to cantaloupe without a value will cause an exception. If I look at the [HTTP message spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), such a header seems to be valid. And even if it is not, I think it's a good idea to let the Cantaloupe server deal with such empty headers.

### Problem
So, for example, right now a request header of: `foo:` will cause the following code to error out:
`/src/main/java/edu/illinois/library/cantaloupe/http/Header.java:57`

### Solution
**A**
My suggestion is that **either** the exception is catched and the **header is simply ignored** at line:
`/src/main/java/edu/illinois/library/cantaloupe/resource/Request.java:63`

OR

**B**
The header value **length check is removed**, so the empty string is stored and used throughout the app. That means changing the following line:

`/src/main/java/edu/illinois/library/cantaloupe/http/Header.java:57` to:
`if (value == null) {`

### Specifics
In our particular case the **X-Forwarded-Proto** header is set by our reverse proxy, but the value is empty. According to the [documentation](https://cantaloupe-project.github.io/manual/3.1/deployment.html#Reverse-Proxying) either a set or missing header is OK. We however have to deal with a header without a value. Setting the `base_uri` doesn't help in this regard.

### PS

I think the Exception message is not as intended, the value should be in the message, not the name:
`/src/main/java/edu/illinois/library/cantaloupe/http/Header.java:57`

```throw new IllegalArgumentException("Illegal value: " + name);```
-->
```throw new IllegalArgumentException("Illegal value: " + value)```

**Comment by RRMoelker** [comment]
Oh, and in case it's not clear. I'm up for creating a solution that can be merged back into the project.

**Comment by adolski** [comment]
Hi @RRMoelker,

Thanks for reporting this. I agree that empty headers should be allowed and I like your "B" solution. You are welcome to submit a PR for this, otherwise I'm happy to do it too, just let me know.

P.S. your P.S. is also correct 😄
