### ISSUE TITLE
"Is alpn-boot on the boot class path?"

### ISSUE THREAD

**Issue by RussellMcOrmond** [cantaloupe-project/cantaloupe#315]
We are using Cantaloupe 4.1.3 within a docker image built from openjdk:8u191-alpine , and recently switched from accessing images on a filesystem to a Swift server using the S3 source feature.

I note in the output from Cantaloupe the following:

```
 Sep 05, 2019 3:51:17 PM okhttp3.internal.platform.Platform log
 INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path
```

This might relate to the various Jetty version changes that happened recently.  This doesn't seem to be generating any issues, so this is more an FYI.

Note: Java is not my area, so I don't know if we should move to a newer version (possibly better tested with Cantaloupe).

**Comment by adolski** [comment]
S3Source was recently modified to use a Minio client, which internally uses an OkHttp client, which is what's logging this. To use HTTP/2 in Java, ALPN support must be available in the JVM, which it wasn't (without a special JAR) until Java 9. This message indicates that the OkHttp client didn't find that support so is falling back to HTTP/1.1.

It should be fine to migrate to a newer Java, if you want to. FWIW, I do development and production in 11 and Cantaloupe 5.0 will require >= 11.

**Comment by RussellMcOrmond** [comment]
As always, thank you very much for the help.

I'm wondering if our old Java is also causing the inconsistent "getMetadata(): Inconsistent metadata read from stream" warnings from Cantaloupe.  We see these when people are using our main application, but if I go to the Cantaloupe URL directly I don't see the error.  I'll try the OpenJDK 11 LTS version and see how things go.

**Comment by RussellMcOrmond** [comment]
We have upgraded to 11.  It didn't solve the "getMetadata()" warnings, so will continue to watch that.

Thank you.

**Comment by adolski** [comment]
I bet that error happens when using Java2dProcessor or JaiProcessor to serve certain source JPEGs? This is a known issue, but I see that it wasn't documented, so I added a note at the end of the Java2dProcessor section of the user manual: https://cantaloupe-project.github.io/manual/4.1/processors.html#Java2dProcessor

**Comment by RussellMcOrmond** [comment]
Thank you. Will look into that alternative.  Are there performance issues with it?

**Comment by adolski** [comment]
With TurboJpegProcessor? It's quite a bit faster, if you consider that an issue :smile:
