### ISSUE TITLE
Internal Server error when HttpSource gets HTTP 401 or 403

### ISSUE THREAD

**Issue by bencomp** [cantaloupe-project/cantaloupe#321]
We are building a IIIF server setup around Cantaloupe (4.1.3) that retrieves JPG2000 images from Islandora over HTTPS. We created an extra HTTP endpoint in Islandora that provides info about accessibility of images and made the delegate script check its output in the `authorize()` method.

However, not all images are accessible by default, and before the `authorize()` method is called, the HEAD request on the image file fails in these cases with an HTTP 403 error returned by Islandora. Cantaloupe does see that it's a 403 status:

https://github.com/cantaloupe-project/cantaloupe/blob/98b962ce58693ba1953eff4ee8d0317bbe214d77/src/main/java/edu/illinois/library/cantaloupe/source/HttpSource.java#L269-L271

But then this `AccessDeniedException` is not handled as such, resulting in HTTP 500 with `HTTP 403` as the message. Could this be changed to return HTTP 403 to the end user? Or is this a configuration/design error on our side?

https://github.com/cantaloupe-project/cantaloupe/blob/98b962ce58693ba1953eff4ee8d0317bbe214d77/src/main/java/edu/illinois/library/cantaloupe/resource/iiif/v2/ImageResource.java#L134-L142

**Comment by adolski** [comment]
Thanks for reporting this. I agree that HTTP 403 should be returned in this case and I'll be pushing a fix shortly.
