### ISSUE TITLE
Enhancement to have a watermark overlay image scaled to fit the entire base image

### ISSUE THREAD

**Issue by cmhdave** [cantaloupe-project/cantaloupe#322]
We have a need to have our watermark overlay image scaled to fit the entire image.  The reason being, images that are hosted come in all different sizes so it's not practical to have one-size watermark image.  Using `repeat` is an option but if you have a HUGE image in your collection and your watermark image is not very big, you get way too many watermarks and it looks kind of comical.

An option we'd like to contribute is a `scaled` option for watermark where the overlay image is scaled to fit inside the image and centered either horizontally or vertically based on the layout of the image compared to the layout of the overlay.

**Comment by adolski** [comment]
Hi @cmhdave,

This sounds like a useful feature. The only thing that really occurs to me is that I hope you can make it respect the overlay inset.

Let me know if you need any assistance.
