### ISSUE TITLE
JPX failing with "Width (0) and height (0) cannot be <= 0"

### ISSUE THREAD

**Issue by ksclarke** [cantaloupe-project/cantaloupe#323]
We have some JPX images that we've created using Kakadu. When we load them into Cantaloupe the info.json file is created with a width and height of the image. When we try to render the image though we get a 500 error and a complaint in the HTTP response that seems to say the height and width are 0:
```
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at edu.illinois.library.cantaloupe.processor.codec.JPEG2000KakaduImageReader.readRegion(JPEG2000KakaduImageReader.java:568)
	at edu.illinois.library.cantaloupe.processor.KakaduNativeProcessor.process(KakaduNativeProcessor.java:264)
```
The 4.1.3 logging that's output has:
```
22:51:30.680 [qtp2114694065-20] DEBUG e.i.l.c.p.c.JPEG2000KakaduImageReader - Rendered region 1,1/0x0; source 0,0/0x0; 0x reduction factor; differential scale 0/10000000
22:51:30.680 [qtp2114694065-20] ERROR e.i.l.c.p.c.JPEG2000KakaduImageReader - Error in Kakadu Region Decompressor:
The `kdu_channel_mapping' object supplied to `kdu_region_decompressor::start'
does not define any channels at all.
```
The 5.0-SNAPSHOT logging is a little different, but it's still seeing the h/w as 0.

I'm just starting to dig into this, but thought I'd post here in case it's something that rings a bell. I can supply a sample JPX if you'd like. I can open the JPX images on my laptop using Gimp and view them, etc. I've used Kakadu to convert back to TIFFs and the TIFFs are fine and readable.

**Comment by adolski** [comment]
Hi, please share one of these files and I'll look into it.

**Comment by ksclarke** [comment]
I zipped the JPX since JPX isn't one of the supported upload file types. So, just unzip first. Thanks.

[ksclarke-test.jpx.zip](https://github.com/cantaloupe-project/cantaloupe/files/3658232/ksclarke-test.jpx.zip)

**Comment by adolski** [comment]
There was a regression in 4.1.1 that broke JPX support. It got fixed in d1717538ce7f5e205cf8193c80a6779449657df5. I can reproduce this in 4.1.3, but it seems to be fixed already on `release/4.1` and `develop` branches.

**Comment by ksclarke** [comment]
Okay, so we can build from release/4.1 until 4.1.4 comes out? Any timeline for that?

**Comment by adolski** [comment]
Correct. 4.1.4 probably within a week or two

**Comment by ksclarke** [comment]
Hmm, for what it's worth (and now that I think of it), I tried the 'develop' branch (5.0-SNAPSHOT) and got an error at that same place. There was a different log message, but it still mentioned h/w being 0.

**Comment by adolski** [comment]
Have you fetched recently?

Are you using a derivative cache? If so, try appending `?cache=false` to the image URL. If that works then you can use the [PurgeItemFromCache method](https://cantaloupe-project.github.io/manual/4.1/remote-management.html#PurgeItemFromCache) to purge these invalid dimensions from the cache.

**Comment by ksclarke** [comment]
Using the 'develop' branch works for us. I had done a fresh checkout before but I did run the 4.1.3 branch before trying the 5.0-SNAPSHOT branch so it must have created a cache that the 5.0-SNAPSHOT run used(?) Good to know about the individual item purge method too, thanks!
