### ISSUE TITLE
ArrayIndexOutOfBoundsException in DelegateProxy

### ISSUE THREAD

**Issue by kaij** [cantaloupe-project/cantaloupe#325]
I'm seeing a sporadic ArrayIndexOutOfBoundsExcpetion in the DelegateProxy class. It looks like this in the log and is handled with a HTTP 500 error.

```
e-prod1-services-iiif-pages | 05:29:59.239 [qtp19986569-45861] DEBUG e.i.l.c.r.i.v.ImageResource - Request headers: Connection: close; X-E-Document: http://m/server/document/render?max_width=600&max_height=600&page_nr=1&url=%2Fdocuments%2FPublications5%2Fe-1234%2Fdata%2Fe-1234.pdf; Host: pages:8182
e-prod1-services-iiif-pages | 05:29:59.239 [qtp19986569-45861] ERROR e.i.l.c.s.DelegateProxy - java.lang.ArrayIndexOutOfBoundsException
e-prod1-services-iiif-pages | 05:29:59.239 [qtp19986569-45861] TRACE e.i.l.c.s.DelegateProxy - invokeUncached(): invoking authorize() with args: (none)
```

There seems to be only one place where an exception is logged, which is at this point: https://github.com/cantaloupe-project/cantaloupe/blob/51e2be77fae1a6bf97ca56b63f8c5a6bc97151e0/src/main/java/edu/illinois/library/cantaloupe/script/DelegateProxy.java#L151 - which is the instantiation of the ruby delegate.

I suspect this might be because of a low memory condition. Restarting the service helped. But I would be interested in any other ideas about why this is happening.

**Comment by adolski** [comment]
Hi @kaij ,

I'm not sure what's happening here. I modified that log statement to log the stack trace. Hopefully that will reveal more information.

**Comment by kaij** [comment]
Thanks @adolski! I keep an eye on it and see if it's possible to reproduce the error somehow (it appear after running fine for >1month in production)

**Comment by adolski** [comment]
Closing as this is probably related to #402
