### ISSUE TITLE
native.jpg not showing

### ISSUE THREAD

**Issue by doobybug** [cantaloupe-project/cantaloupe#326]
Hi I have set up apache proxies to link to cantaloupe, and default.jpg images are loaded however native.jpg are giving me the following error:

No enum constant edu.illinois.library.cantaloupe.resource.iiif.v2.Quality.NATIVE

Any idea why and how I can solve it pls?

**Comment by regisrob** [comment]
The "native" quality is from Image API 1.1 (https://iiif.io/api/image/1.1/#4-4-quality), it has been deprecated and somehow replaced by "default" in 2.1 (https://iiif.io/api/image/2.1/#quality).
So you cannot make image requests with "native.jpg" if your Cantaloupe server has "endpoint.iiif.2.enabled = true" (https://github.com/cantaloupe-project/cantaloupe/blob/develop/cantaloupe.properties.sample#L82)

**Comment by adolski** [comment]
`native` is one of the IIIF Image API 1.x qualities. In Cantaloupe the Image API 1.x and 2.x endpoints are separate. You must either change `native` to `default` or use the 1.x endpoint (at `/iiif/1`) instead.
