### ISSUE TITLE
Cookies header?

### ISSUE THREAD

**Issue by ksclarke** [cantaloupe-project/cantaloupe#329]
I may be doing something wrong. When using the delegate script with 4.1.4, I'm seeing something other than what the documentation seems to imply I should.

In my authorize() method, I do:

    @cookies = context['cookies']
    logger = Java::edu.illinois.library.cantaloupe.script.Logger
    logger.info @cookies.to_s

The hash that I see looks like the following (which I believe is a standard cookie request header):

    {"Cookie"=>"initialization_vector=abcdefghijklmnop; sinai_authenticated=D4B197B706847D941E2232E7882258B2A71EC589A02A8F957AD5BAEBECB0528E"}

But from the documentation I was expecting to see cookies in the form of:

    {"initialization_vector"=>"abcdefghijklmnop", "sinai_authenticated"=>"D4B197B706847D941E2232E7882258B2A71EC589A02A8F957AD5BAEBECB0528E"}

I'm running Cantaloupe from the jar file in a docker container on my localhost. I'm using Postman to send cookies.

Has there been a change that the documentation has not caught up to, am I misreading the delegate script documentation/comments, or do you have any idea what might be going on? Thanks.

**Comment by adolski** [comment]
Thanks for pointing this out. The documentation is correct but the context hash structure isn't.

A fix has been committed to `develop`. To avoid breaking users' scripts, I'm just going to keep this bug around in the 4.1 series.
