### ISSUE TITLE
[Meta] Migrate from Maven to Gradle?

### ISSUE THREAD

**Issue by MorrisonCole** [cantaloupe-project/cantaloupe#337]
First off, thanks for the awesome project @adolski! 

I noticed the `5.x` branches target Java 11, so figured there must be at least some appetite for adopting new technologies around here!

I couldn't find any issues about this so forgive me if it's already been discussed, but presuming you're familiar with [Gradle](https://gradle.org/), have you considered porting the build to use it?

I think there are a fair few benefits which I can go into if you're not already familiar, but presuming you are, I'm happy to give it a go and submit a PR! 😄

**Comment by adolski** [comment]
Hi @MorrisonCole ,

I'm not really familiar with Gradle. I've been using Maven for no real reason other than I can get it to do what I need most of the time. But I'm open to looking into Gradle if it will work better.

**Comment by cmhdave** [comment]
I am a heavy Gradle user BUT I see no real reason to switch to Gradle when Maven is working fine.  

- The benefits I've found with using Gradle is that I am able to create Groovy code within the buildscript that does things when a plugin doesn't exist.
- We also found that our Maven builds needed to rely on ancient Ant scripts to perform certain tasks and we don't have that problem at all with Gradle.
- Finally the dependency management in Gradle is a bit more robust.  You are able to manipulate a little more what transitive dependencies are pulled in (based on capability and not just version)

This all being said I never recommend someone switching for the sake of switching.  Both are very capable build tools.

**Comment by MorrisonCole** [comment]
> This all being said I never recommend someone switching for the sake of switching. Both are very capable build tools.

Certainly agree with this. Gradle can certainly be faster when configured correctly too which is one more benefit amongst others, but the differences are fairly minor in the grand scheme of things and since it's mainly @adolski developing this project I think the 'best' build tool is probably the one they're most familiar with 😄.

Feel free to close this - brought it up mainly because I was interested in having a go at it! :)
