### ISSUE TITLE
Nothing is getting written to the access.log

### ISSUE THREAD

**Issue by RodBruce** [cantaloupe-project/cantaloupe#338]
I upgraded from 4.0.3 to 4.1.4. I copied the cantaloupe.properties file and made the recommended changes from the UPGRADING.md. Nothing changed in my LOGGING section. The application log and error log are both getting written to as expected but nothing is getting written to the access.log. This is happening on both servers that I have upgraded. I double checked and there are no permission issues. I'm including the Logging section of my properties file.

Thanks

[cantaloupe.properties.logging.txt](https://github.com/cantaloupe-project/cantaloupe/files/3947549/cantaloupe.properties.logging.txt)

**Comment by adolski** [comment]
Thanks for reporting this, @RodBruce. It looks like the access log was broken by a Jetty upgrade some time ago. This has been fixed in the `release/4.1` branch for inclusion in 4.1.5.

**Comment by adolski** [comment]
This isn't fixed after all, and it will probably remain broken in the 4.1.x series (see #339 for background).

**Comment by adolski** [comment]
Fixed by aab2b909fe0ed0ecc21bfbd6f2a2264ddec2a48b
