### ISSUE TITLE
Cached info.json served for unauthorized request

### ISSUE THREAD

**Issue by adam-vessey** [cantaloupe-project/cantaloupe#347]
With an `authorize` method in the `delegates.rb` which checks that a valid token is passed in an HTTP header, performing:
* A hit against an info.json as an allowed user (also loading the tiles and the like via OpenSeadragon); and then,
* A hit against the same info.json as a forbidden user, expecting a 403 and some form of blank/error page body

The forbidden user does get a 403; however, the page body still contains the info.json.
Passing the `?cache=false` flag causes a more-expected "403 Forbidden" error page in the body.

Tracing through...:
* [Our `delegate.rb` returns boolean](https://github.com/cantaloupe-project/cantaloupe/blob/0dc0dec137da22ad8e37e7e22355ca360c729b98/src/main/java/edu/illinois/library/cantaloupe/auth/DelegateAuthorizer.java#L49-L51), which is [coerced into a 403](https://github.com/cantaloupe-project/cantaloupe/blob/0dc0dec137da22ad8e37e7e22355ca360c729b98/src/main/java/edu/illinois/library/cantaloupe/auth/AuthInfo.java#L32-L38)
* ... which triggers an [exception](https://github.com/cantaloupe-project/cantaloupe/blob/0dc0dec137da22ad8e37e7e22355ca360c729b98/src/main/java/edu/illinois/library/cantaloupe/resource/AbstractResource.java#L266-L272), 
* [The exception is ignored](https://github.com/cantaloupe-project/cantaloupe/blob/0dc0dec137da22ad8e37e7e22355ca360c729b98/src/main/java/edu/illinois/library/cantaloupe/resource/iiif/v2/InformationResource.java#L65-L68), despite bearing a 403, and proceeding to provide the data from the cache, despite being forbidden to its contents.

... This seems like it has the potential to leak information to users who are not authorized to see it... just the metadata it seems, but... is non-zero. Thoughts?

**Comment by adolski** [comment]
This is indeed a bug. Only 401s are supposed to "leak" [as required by the Authentication API](https://iiif.io/api/auth/1.0/#interaction-with-access-controlled-resources). Thanks for pointing it out.
