### ISSUE TITLE
Boolean Configuration Inheritance

### ISSUE THREAD

**Issue by adam-vessey** [cantaloupe-project/cantaloupe#350]
As per the docs, the [`extends`](https://cantaloupe-project.github.io/manual/4.1/configuration.html#Inheritance) property allows for files to be used which override another, indicating:

> Keys in child files override ones in parent files.

However: Attempting to override boolean values does not work.

For example: Leaving the default/sample `cache.server.derivative.enabled` value as `false`, attempting to enable in an override file, setting to `true` fails... leaving the cache disabled.

... The override file _is_ being used, as there's other effects which are being used, such as pointing at a different `delegate_script.pathname`.

Bit of tracing around... is it just [missing a `break` in the `HeritablePropertiesConfiguration.readBoolean()`](https://github.com/cantaloupe-project/cantaloupe/blob/df5fe2457b2277000ce4a468d7fe7dc576237e2e/src/main/java/edu/illinois/library/cantaloupe/config/HeritablePropertiesConfiguration.java#L133-L137)? There are `break` statements in:
* [`readDouble()`](https://github.com/cantaloupe-project/cantaloupe/blob/df5fe2457b2277000ce4a468d7fe7dc576237e2e/src/main/java/edu/illinois/library/cantaloupe/config/HeritablePropertiesConfiguration.java#L182)
* [`readFloat()`](https://github.com/cantaloupe-project/cantaloupe/blob/df5fe2457b2277000ce4a468d7fe7dc576237e2e/src/main/java/edu/illinois/library/cantaloupe/config/HeritablePropertiesConfiguration.java#L229)
* [`readInteger()`](https://github.com/cantaloupe-project/cantaloupe/blob/df5fe2457b2277000ce4a468d7fe7dc576237e2e/src/main/java/edu/illinois/library/cantaloupe/config/HeritablePropertiesConfiguration.java#L276)
* [`readLong()`](https://github.com/cantaloupe-project/cantaloupe/blob/df5fe2457b2277000ce4a468d7fe7dc576237e2e/src/main/java/edu/illinois/library/cantaloupe/config/HeritablePropertiesConfiguration.java#L351); and,
* [`readString()`](https://github.com/cantaloupe-project/cantaloupe/blob/df5fe2457b2277000ce4a468d7fe7dc576237e2e/src/main/java/edu/illinois/library/cantaloupe/config/HeritablePropertiesConfiguration.java#L424)

... `readBoolean()` appears to be the odd one out?

**Comment by adam-vessey** [comment]
A bit of experimentation expanding on the tests (realizing now that I missed `readLong()`), and throwing in the break: https://github.com/cantaloupe-project/cantaloupe/compare/v4.1.5...adam-vessey:boolean-inheritance

**Comment by adolski** [comment]
Thanks @adam-vessey! Your diagnosis was correct. This will get merged into `develop` shortly.
