### ISSUE TITLE
URL identifier is being modified based on implied ScaleConstraint

### ISSUE THREAD

**Issue by cmhdave** [cantaloupe-project/cantaloupe#353]
For our implementation of Cantaloupe we have the need to include two "parameters" that can identify a single item.  A "collection id" and an "item id".  We accomplish this by concatenating the values together in our URL identifier like so "/iiif/2/collection-id:123/full/full/10/default.jpg"

Recently I was debugging one of our collections that happened to be named with a "-2" at the end... so the identifier was essentially "collection-id-2:123".  

According to the IIIF Image API standard this should be perfectly 'legal'.  I checked all the different versions of the specification to make sure and it says, "The API places no restrictions on the form of the identifiers that a server may use or support. All special characters (e.g. ? or #) must be URI encoded to avoid unpredictable client behaviors. The URI syntax relies upon slash (/) separators so any slashes in the identifier must be URI encoded (also called “percent encoded”)."

In the case of our identifier both the "-" and ":" are URL safe characters so there is no need to URL encode either of them within the spec.  

That leads me to this method which seems to be causing our bug:

https://github.com/cantaloupe-project/cantaloupe/blob/df5fe2457b2277000ce4a468d7fe7dc576237e2e/src/main/java/edu/illinois/library/cantaloupe/image/ScaleConstraint.java#L48

I don't see in the specification anywhere that defines a URL being allowed to modify the scale of an image based on a suffix added to it's identifier.  This suggests to me that this is probably a special case to cover a non-IIIF url.

I think this should either be parameterized (i.e. can be configured to occur based on a configuration value in cantaloupe.properties but disabled by default) or this special kind of scenario should be handled in the delegates.rb or maybe by a mod_rewrite rule by an Apache HTTPD server fronting a Cantaloupe server.

**Comment by adolski** [comment]
The above commit adds a `scale_constraints.delimiter` config key. I didn't notice you were working on something else. I will have to think more about whether I want to make scale constraints disable-able.

**Comment by cmhdave** [comment]
Ah! This is great.  Making it disable-able was only a work-around.  Your solution is more elegant.

**Comment by cmhdave** [comment]
Just tested your fix out @adolski and it works like a charm for us.  Thanks!
