### ISSUE TITLE
Can PDF page argument  (PDFbox, etc) be used to produce a page specific info.json?

### ISSUE THREAD

**Issue by DiegoPino** [cantaloupe-project/cantaloupe#359]
Hi @adolski this is question, not a bug report or feature request.

Its there a way (planned? existing?) to ask cantaloupe for a `info.json` for a specific `?page` argument?

Right now we can access each page via your extension extension (thanks, so useful) but i can not get the processor to generate a info.json for a specific page, i always get the first page. 

I don't seem to find anything that makes me think URI Get arguments are passed to the processor or used in the Image id here https://github.com/cantaloupe-project/cantaloupe/blob/release/4.1/src/main/java/edu/illinois/library/cantaloupe/cache/InfoService.java

Just a question. We can probably live without getting the sizes for each page, but could be useful for other use cases when using/passing an argument (whatever it is) is required/accepted by the processor to do its job and could change the output. Thanks

**Comment by adolski** [comment]
Hi @DiegoPino,

This actually is a bug. I will push a fix soon for inclusion in 4.1.6.

**Comment by DiegoPino** [comment]
@adolski thank you so much 👍 Hope all is well there. Stay safe and thanks again
