### ISSUE TITLE
Update JRuby dependency to support new TLS ciphers with Net::HTTP

### ISSUE THREAD

**Issue by bencomp** [cantaloupe-project/cantaloupe#362]
Recently our IT department limited the supported ciphers on a server that we consult via HTTPS/TLS in the `authorize()` method in delegates.rb with Cantaloupe 4.1.5. The code uses the Ruby `Net::HTTP` library. After the update we started seeing errors mentioning an SSL handshake failure.

After some searching I'm pretty certain that JRuby's lack of support for the new ciphers causes the error message `(SSLError) Received fatal alert: handshake_failure` during the script execution within the `DelegateAuthorizer`. See the screenshot for a bit more of the stacktrace:

![ssl-handshake-failed](https://user-images.githubusercontent.com/1303898/80096835-873a6480-856a-11ea-9283-27f90422d075.png)

The new and only supported ciphers (supported on our servers, that is) are `ECDHE-RSA-AES128-GCM-SHA256` and `ECDHE-RSA-AES256-GCM-SHA384`. Support for these ciphers was added to [jruby-openssl v0.10.3](https://github.com/jruby/jruby-openssl/releases/tag/v0.10.3), which seems to be part of JRuby starting with [release 9.2.10.0](https://github.com/jruby/jruby/releases/tag/9.2.10.0). This is all very recent, though I understand that IT departments are keeping a closer eye on security with more people working from home, so I expect that more people may run into similar incompatibility issues. Could you try to update JRuby to >=9.2.10.0? I tried building Cantaloupe 4.1.5 with JRuby 9.2.11.1 on my Mac with Java 13, but lots of tests errored, so I think something else is happening there.

I hope this issue saves other people some time. In the meantime we will try to call Java from delegates.rb for the HTTPS call, to work around JRuby HTTPS calls. Hopefully our JRE does support the new ciphers…

**Comment by adolski** [comment]
Hi @bencomp, thanks for pointing this out. I think it's OK to update JRuby to the latest version for 4.1.6. I can't think of any incompatibilities it would introduce.

The test errors you encountered are probably something else. I was able to swap in the latest version with no other changes.
