### ISSUE TITLE
Why does building in my docker container fail (Unknown host repository.codehaus.org)?

### ISSUE THREAD

**Issue by kramer65** [cantaloupe-project/cantaloupe#363]
I'm running Cantaloupe in production using Docker. For this I've got a `Dockerfile` of which this is the start:

```
FROM ubuntu:18.04 AS base

ENV CANTALOUPE_VERSION="4.1.5"

EXPOSE 8080

RUN apt update -y && \
    apt install -y --no-install-recommends \
      wget unzip curl net-tools \
      graphicsmagick imagemagick ffmpeg python \
      maven default-jre
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

RUN wget -O cantaloupe-git.zip https://github.com/cantaloupe-project/cantaloupe/archive/v${CANTALOUPE_VERSION}.zip
RUN unzip cantaloupe-git.zip

RUN cd /tmp/cantaloupe-${CANTALOUPE_VERSION} && mvn clean package -DskipTests
# and after this some more stuff..
```

This Dockerfile fails on the last line though, with the following error:

> [ERROR] Failed to execute goal on project cantaloupe: Could not resolve dependencies for project edu.illinois.library.cantaloupe:cantaloupe:war:4.1.5: Failed to collect dependencies at it.geosolutions.imageio-ext:imageio-ext-tiff:jar:1.1.19 -> it.geosolutions.imageio-ext:imageio-ext-utilities:jar:1.1.19 -> javax.media:jai_codec:jar:1.1.3: Failed to read artifact descriptor for javax.media:jai_codec:jar:1.1.3: Could not transfer artifact javax.media:jai_codec:pom:1.1.3 from/to codehaus (http://repository.codehaus.org/): repository.codehaus.org: Name or service not known: Unknown host repository.codehaus.org: Name or service not known -> [Help 1]

Of this error, the last part is interesting: **Name or service not known: Unknown host repository.codehaus.org**

`codehaus.org` is indeed offline, and according to [this post](https://stackoverflow.com/a/31230193/1650012) that is already since at least 2015 (!!).

The weird thing is that this Dockerfile used to work fine until about at least a month ago. 

Also, I don't see anyone else with this issue on the issue tracker here.

Am I doing something wrong in my Dockerfile? All tips are welcome!

**Comment by adolski** [comment]
Hi @kramer65 , I see that you found a workaround for this in https://github.com/geosolutions-it/imageio-ext/issues/214. I hope they will fix this in their POM soon.

**Comment by kramer65** [comment]
@adolski - True, I found a workaround. But it isn't pretty.

Would be great if this would be fixed indeed. I'm just puzzled nobody else here has that problem.

**Comment by kramer65** [comment]
@adolski - I see you also implemented my fix directly in cantaloupe itself. In which release will that be published? Because then I need to remove the fix again from my own code.

**Comment by adolski** [comment]
This should now be resolved without having to add an `~/.m2/settings.xml`.
