### ISSUE TITLE
Clearing cache selectively

### ISSUE THREAD

**Issue by msimkunas** [cantaloupe-project/cantaloupe#367]
Is it possible to selectively clear the cache for a single identifier only?

I have managed to do this manually by computing an MD5 hash of the identifier and removing the corresponding files in the cache directory tree but this feels like a wrong approach.

I'm using the `FilesystemCache` implementation on Cantaloupe 4.1.5.

**Comment by giancarlobi** [comment]
@msimkunas Not sure if useful for you, I use administrative HTTP API with this command (bash/terminal):
`wget -q --server-response --user=*** --password=*** --post-data='{ "verb" : "PurgeItemFromCache", "identifier" : "[your object identifier]" }' --header=Content-Type:application/json http://[CantaloupeIP]:8182/tasks`

**Comment by msimkunas** [comment]
Thanks for such a quick response! I didn't know that this API route even existed. Is this documented somewhere?

**Comment by giancarlobi** [comment]
@msimkunas for 4.1 here: https://cantaloupe-project.github.io/manual/4.1/remote-management.html
