### ISSUE TITLE
Ability to set or change ?page= via delegate.rb script

### ISSUE THREAD

**Issue by cmhdave** [cantaloupe-project/cantaloupe#372]
It might be easier to describe our use case than it would to just ask for what I am trying to figure out how to do.

We have a database that describes all our items that we serve up through Cantaloupe.  One of the things we would like to serve up as images through Cantaloupe are individual PDF pages.  I know that currently this is accomplished with the `?page=` query string parameter.  However what we do is we have a separate item ID for each page of a PDF.  So for example we might store in our database something like this:

item1 - PDF parent - this_is_the_pdf_file.pdf - parentId=-1
item2 - PDF Page 1 - this_is_the_pdf_file.pdf - parentId=1 - page=1
item3 - PDF Page 2 - this_is_the_pdf_file.pdf - parentId=1 - page=2

So if we access item2, we know to open the parent PDF file to page=1

We would like to be able to pass that along from the delegates.rb script when we do our item lookup logic. So when someone requests /iiif/2/item2/full/full/0/default.jpg we take that identifier, look up in the database which file to use and which page number to load.

This is important as the identifier = item2 has meaning.  In our system it is a distinctly identifiable item with unique metadata.  Just passing in /iiif/2/item1/full/full/0/default.jpg?page=1 won't identify the item the same way we do everywhere else in our system.  It also isn't respected by Mirador so we end up with a manifest of "item1" images.

The best way we can think to solve this in our use case would be for us to somehow synthetically insert a "page" operation from the delegates.rb script.  I have no idea how this could be accomplished... but that seems like the most generic resolution so we wouldn't be asking for a bespoke solution to a unique problem.  That way anyone could make use of modifying page= from the delegates.rb script.

**Comment by adolski** [comment]
Hi @cmhdave,

There is a related discussion in #344 that proposes moving the `page` query argument into the identifier portion of the URI. I believe that might be able to solve your problem depending on how it's eventually implemented.

**Comment by cmhdave** [comment]
Resolved by #344
