### ISSUE TITLE
CustomDelegate#authorize is not called when the image has already been cached

### ISSUE THREAD

**Issue by gigamorph** [cantaloupe-project/cantaloupe#374]
I'm using v4.1.5 with source cache and derivative cache enabled, both FilesystemCache. I am also using the delegates script to authorize requests based on the content of the Authorization header.

For me, authorize() does not get called when the image has already been cached. For example, if I make authorize() return true if the "Authorization" header is set to "pass" and false otherwise, 
(1) I make a request for the image using the correct header value, and I get the image returned,
(2) I subsequently make a request using an empty header, and the authorize() call is skipped and I still get the image back when I should be getting a 403,
(3) if I make a request to info.json instead of the image itself (with an empty, incorrect header), the log indicates authorized() does get called and returns false, but I still get the info.json back instead of 403.

**Comment by cmhdave** [comment]
Do you have `delegate_script.cache.enabled = true` in your cantaloupe.properties file?  This could be causing you a problem as it would skip invocation of your delegate script and try to return a cached result from a previous call.

**Comment by gigamorph** [comment]
It is set to false. My production configuration is a bit more complicated but here's a simpler configuration I tried to reproduce the problem:

<details>
<summary>cantaloupe.properties</summary>
temp_pathname =

http.enabled = true
http.host = 0.0.0.0
http.port = 8182
http.http2.enabled = false

https.enabled = false
https.host = 0.0.0.0
https.port = 8183
https.http2.enabled = false

https.key_store_type = JKS
https.key_store_password = myPassword
https.key_store_path = /path/to/keystore.jks
https.key_password = myPassword

http.accept_queue_limit =

base_uri =

slash_substitute =

max_pixels = 100000000

max_scale = 1.0
print_stack_trace_on_error_pages = true


delegate_script.enabled = true

delegate_script.pathname = delegates.rb

delegate_script.cache.enabled = false


endpoint.iiif.1.enabled = false

endpoint.iiif.2.enabled = true

endpoint.iiif.content_disposition = inline

endpoint.iiif.min_size = 64

endpoint.iiif.min_tile_size = 512

endpoint.iiif.2.restrict_to_sizes = false

endpoint.admin.enabled = false
endpoint.admin.username = admin
endpoint.admin.secret =

endpoint.api.enabled = false

endpoint.api.username =
endpoint.api.secret =


source.static = FilesystemSource

source.delegate = false


FilesystemSource.lookup_strategy = BasicLookupStrategy

FilesystemSource.BasicLookupStrategy.path_prefix = /Users/sk/Desktop/cantaloupe/cantaloupe-4.1.5/source/

FilesystemSource.BasicLookupStrategy.path_suffix =


HttpSource.allow_insecure = false

HttpSource.request_timeout =

HttpSource.lookup_strategy = BasicLookupStrategy

HttpSource.BasicLookupStrategy.url_prefix = http://localhost/images/

HttpSource.BasicLookupStrategy.url_suffix =

HttpSource.BasicLookupStrategy.auth.basic.username =
HttpSource.BasicLookupStrategy.auth.basic.secret =

HttpSource.chunking.enabled = true

HttpSource.chunking.chunk_size = 512K

HttpSource.chunking.cache.enabled = true

HttpSource.chunking.cache.max_size = 5M


S3Source.endpoint =

S3Source.access_key_id =
S3Source.secret_key =

S3Source.lookup_strategy = BasicLookupStrategy

S3Source.BasicLookupStrategy.bucket.name =

S3Source.BasicLookupStrategy.path_prefix =

S3Source.BasicLookupStrategy.path_suffix =

S3Source.chunking.enabled = true

S3Source.chunking.chunk_size = 512K

S3Source.chunking.cache.enabled = true

S3Source.chunking.cache.max_size = 5M


AzureStorageSource.account_name =

AzureStorageSource.account_key =

AzureStorageSource.container_name =

AzureStorageSource.lookup_strategy = BasicLookupStrategy

AzureStorageSource.chunking.enabled = true

AzureStorageSource.chunking.chunk_size = 512K

AzureStorageSource.chunking.cache.enabled = true

AzureStorageSource.chunking.cache.max_size = 5M



JdbcSource.url = jdbc:postgresql://localhost:5432/my_database
JdbcSource.user = postgres
JdbcSource.password = postgres

JdbcSource.connection_timeout = 10




processor.selection_strategy = AutomaticSelectionStrategy


processor.ManualSelectionStrategy.avi = FfmpegProcessor
processor.ManualSelectionStrategy.bmp =
processor.ManualSelectionStrategy.dcm = ImageMagickProcessor
processor.ManualSelectionStrategy.flv = FfmpegProcessor
processor.ManualSelectionStrategy.gif =
processor.ManualSelectionStrategy.jp2 = KakaduNativeProcessor
processor.ManualSelectionStrategy.jpg =
processor.ManualSelectionStrategy.mov = FfmpegProcessor
processor.ManualSelectionStrategy.mp4 = FfmpegProcessor
processor.ManualSelectionStrategy.mpg = FfmpegProcessor
processor.ManualSelectionStrategy.pdf = PdfBoxProcessor
processor.ManualSelectionStrategy.png =
processor.ManualSelectionStrategy.tif =
processor.ManualSelectionStrategy.webm = FfmpegProcessor
processor.ManualSelectionStrategy.webp = ImageMagickProcessor

processor.ManualSelectionStrategy.fallback = Java2dProcessor




processor.stream_retrieval_strategy = CacheStrategy

processor.fallback_retrieval_strategy = DownloadStrategy

processor.dpi = 150

processor.background_color = white

processor.downscale_filter = bicubic
processor.upscale_filter = bicubic

processor.sharpen = 0

processor.metadata.preserve = false

processor.metadata.respect_orientation = false

processor.jpg.progressive = true

processor.jpg.quality = 80

processor.tif.compression = LZW


processor.imageio.bmp.reader =
processor.imageio.gif.reader =
processor.imageio.gif.writer =
processor.imageio.jpg.reader =
processor.imageio.jpg.writer =
processor.imageio.png.reader =
processor.imageio.png.writer =
processor.imageio.tif.reader =
processor.imageio.tif.writer =


FfmpegProcessor.path_to_binaries =


GraphicsMagickProcessor.path_to_binaries =


ImageMagickProcessor.path_to_binaries =


KakaduDemoProcessor.path_to_binaries =


OpenJpegProcessor.path_to_binaries =


cache.client.enabled = true
cache.client.max_age = 2592000
cache.client.shared_max_age =
cache.client.public = true
cache.client.private = false
cache.client.no_cache = false
cache.client.no_store = false
cache.client.must_revalidate = false
cache.client.proxy_revalidate = false
cache.client.no_transform = true



cache.server.source = FilesystemCache

cache.server.source.ttl_seconds = 2592000

cache.server.derivative.enabled = true

cache.server.derivative = FilesystemCache

cache.server.derivative.ttl_seconds = 2592000

cache.server.info.enabled = true

cache.server.purge_missing = false

cache.server.resolve_first = false

cache.server.worker.enabled = false

cache.server.worker.interval = 86400


FilesystemCache.pathname = /Users/sk/Desktop/cantaloupe/cantaloupe-4.1.5/cache

FilesystemCache.dir.depth = 3

FilesystemCache.dir.name_length = 2


HeapCache.target_size = 2G

HeapCache.persist = false

HeapCache.persist.filesystem.pathname = /var/cache/cantaloupe/heap.cache


JdbcCache.url = jdbc:postgresql://localhost:5432/cantaloupe
JdbcCache.user = postgres
JdbcCache.password =

JdbcCache.connection_timeout = 10

JdbcCache.derivative_image_table = derivative_cache
JdbcCache.info_table = info_cache


S3Cache.endpoint =

S3Cache.access_key_id =
S3Cache.secret_key =

S3Cache.bucket.name =

S3Cache.object_key_prefix =

S3Cache.max_connections =


AzureStorageCache.account_name =
AzureStorageCache.account_key =

AzureStorageCache.container_name =

AzureStorageCache.object_key_prefix =


RedisCache.host = localhost
RedisCache.port = 6379
RedisCache.ssl = false
RedisCache.password =
RedisCache.database = 0


overlays.enabled = false

overlays.strategy = BasicStrategy

overlays.BasicStrategy.type = image

overlays.BasicStrategy.image = /path/to/overlay.png

overlays.BasicStrategy.string = Copyright © My Great Organization\nAll rights reserved.

overlays.BasicStrategy.string.font = Helvetica

overlays.BasicStrategy.string.font.size = 24

overlays.BasicStrategy.string.font.min_size = 18

overlays.BasicStrategy.string.font.weight = 1.0

overlays.BasicStrategy.string.glyph_spacing = 0.02

overlays.BasicStrategy.string.color = white

overlays.BasicStrategy.string.stroke.color = black

overlays.BasicStrategy.string.stroke.width = 1

overlays.BasicStrategy.string.background.color = rgba(0, 0, 0, 100)

overlays.BasicStrategy.position = bottom right

overlays.BasicStrategy.inset = 10

overlays.BasicStrategy.output_width_threshold = 400

overlays.BasicStrategy.output_height_threshold = 300


redaction.enabled = false



log.application.level = debug
log.application.ConsoleAppender.enabled = true

log.application.FileAppender.enabled = false
log.application.FileAppender.pathname = /path/to/logs/application.log
log.application.RollingFileAppender.enabled = false
log.application.RollingFileAppender.pathname = /path/to/logs/application.log
log.application.RollingFileAppender.policy = TimeBasedRollingPolicy
log.application.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = /path/to/logs/application-%d{yyyy-MM-dd}.log
log.application.RollingFileAppender.TimeBasedRollingPolicy.max_history = 30

log.application.SyslogAppender.enabled = false
log.application.SyslogAppender.host =
log.application.SyslogAppender.port = 514
log.application.SyslogAppender.facility = LOCAL0



log.error.FileAppender.enabled = false
log.error.FileAppender.pathname = /path/to/logs/error.log
log.error.RollingFileAppender.enabled = false
log.error.RollingFileAppender.pathname = /path/to/logs/error.log
log.error.RollingFileAppender.policy = TimeBasedRollingPolicy
log.error.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = /path/to/logs/error-%d{yyyy-MM-dd}.log
log.error.RollingFileAppender.TimeBasedRollingPolicy.max_history = 30


log.access.ConsoleAppender.enabled = false

log.access.FileAppender.enabled = false
log.access.FileAppender.pathname = /path/to/logs/access.log

log.access.RollingFileAppender.enabled = false
log.access.RollingFileAppender.pathname = /path/to/logs/access.log
log.access.RollingFileAppender.policy = TimeBasedRollingPolicy
log.access.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = /path/to/logs/access-%d{yyyy-MM-dd}.log
log.access.RollingFileAppender.TimeBasedRollingPolicy.max_history = 30

log.access.SyslogAppender.enabled = false
log.access.SyslogAppender.host =
log.access.SyslogAppender.port = 514
log.access.SyslogAppender.facility = LOCAL0

</details>

**Comment by gigamorph** [comment]
Weird. It seems I can't reproduce the problem with the vanilla settings any more. Please give a few more days, or you can close this issue for now if necessary. Sorry about that.

**Comment by adolski** [comment]
Hi @gigamorph,

Could the `cache.server.resolve_first` key have had something to do with this? This may be a quirk of the 4.1.x series.

**Comment by cmhdave** [comment]
Along these lines, @adolski should the `retrieveFromCacheOrInvoke` in `JRubyDelegateProxy` always invokeUncached for `authorize()`?  Or maybe make it a setting to make sure `authorize()` is not cached?  I would love to be able to use the delegate cache but we're forced to disable it because someone who is authorized to view an image may cache the response and then next person that comes in that isn't authorized gets the cached value.

On the flip side of this... if someone comes in and isn't authorized to view the image comes first and the next person that IS authorized comes in, they get the "unauthorized" delegate cache and won't see the image.

**Comment by gigamorph** [comment]
@adolski @cmhdave 

Thank you for your response. I tried setting `cache.server.resolve_first` to true and it seems to behave correctly now. I think I'll use that setting for now, but would you say this is a bug?
