### ISSUE TITLE
Server inode limit reached, purge not triggered.

### ISSUE THREAD

**Issue by Ra1phM** [cantaloupe-project/cantaloupe#379]
Hi,

I am running Cantaloupe 4.1.5 on an Ubuntu 18 Server and at some point, the server was not responding correctly anymore.

The health check gave me the following:

```
WARN  e.i.l.c.s.HealthChecker - Health check completed in 8 msec: RED: FilesystemCache: /var/cache/cantaloupe/source/4c/3b/43: No space left on device
```

A `df -i` showed me that the usage of INodes was 100%.

I can purge manually via the API and then it all works fine, but I understand that the worker should do that.

Here is my configuration for the purge:

```
cache.server.source = FilesystemCache
cache.server.source.ttl_seconds = 10800
cache.server.derivative.enabled = false
cache.server.derivative =
cache.server.derivative.ttl_seconds = 10800
cache.server.info.enabled = true
cache.server.purge_missing = false
cache.server.resolve_first = false
cache.server.worker.enabled = true
cache.server.worker.interval = 10800
```

What am I missing?

Thanks,

Ralph

**Comment by adolski** [comment]
Hi @Ra1phM ,

1. Do you see any log entries from `e.i.l.c.cache.CacheWorker`? It will log at info level every time it starts and stops running.
2. Was the cache worker enabled when the application was started? (It can't be enabled or disabled while the application is running.)
3. Did the filesystem fill up between worker intervals?

**Comment by Ra1phM** [comment]
Hi,

Thanks for your reply.

(1) I checked and, indeed, the CacheWorker seems to work. From the log, I think your (3) point is correct as well, the system fills up inbetween 2 workers.
(2) The cache worker was always on and whenever I change a configuration I restart the app.

Here are the log entries (Health checks are called every few seconds by the load balancer):

```
2020-06-10 15:44:27,850 INFO [http-nio-8080-exec-11] e.i.l.c.r.a.HealthResource [AbstractResource.java:117] Handling GET /image/health
2020-06-10 15:44:27,858 WARN [http-nio-8080-exec-11] e.i.l.c.s.HealthChecker [HealthChecker.java:290] Health check completed in 8 msec: RED: FilesystemCache: /var/cache/cantaloupe/source/a7/e0/a8: No space left on device

2020-06-10 15:44:28,934 INFO [pool-3-thread-1] e.i.l.c.c.CacheWorker [CacheWorker.java:27] Working...

2020-06-10 15:44:32,849 INFO [http-nio-8080-exec-1] e.i.l.c.r.a.HealthResource [AbstractResource.java:117] Handling GET /image/health
2020-06-10 15:44:32,861 INFO [http-nio-8080-exec-7] e.i.l.c.r.a.HealthResource [AbstractResource.java:117] Handling GET /image/health
(....)
2020-06-10 15:45:08,322 INFO [http-nio-8080-exec-5] e.i.l.c.r.a.HealthResource [AbstractResource.java:117] Handling GET /image/health
2020-06-10 15:45:11,316 INFO [pool-3-thread-1] e.i.l.c.c.CacheWorker [CacheWorker.java:60] Done working. Next shift starts in 10800 seconds.
2020-06-10 15:45:13,328 INFO [http-nio-8080-exec-6] e.i.l.c.r.a.HealthResource [AbstractResource.java:117] Handling GET /image/health
2020-06-10 15:45:13,335 INFO [http-nio-8080-exec-3] e.i.l.c.r.a.HealthResource [AbstractResource.java:117] Handling GET /image/health
```

This is quite worrying because we do not have yet live traffic on the application.

The issue is really not the storage, but the number of directory and files used by the system. What would be the ideal solution to solve this?
1. Make the worker work much more often? Now it is running every 3h, maybe going down to 1h or even less?
2. Is there any configuration (like FilesystemCache.dir.depth) that could help to reduce the number of inodes used?
3. Add a cron job that checks the inode limit and runs the worker via the API in case of emergency?

Thanks for your help,

Ralph

**Comment by Ra1phM** [comment]
After some monitoring, I don't quite understand what the worker is doing. The number of inodes does not seem to reduce after the worker runs. Only calling the API with `{ "verb" : "PurgeCache" }` truly empties the cache folder and reduces the number of inodes.

**Comment by adolski** [comment]
The worker is telling the cache (FilesystemCache) to purge invalid content, equivalent to what the [PurgeInvalidFromCache](https://cantaloupe-project.github.io/manual/4.1/remote-management.html#PurgeInvalidFromCache) API verb would do.

If you set the log level to trace, you should see some log lines from FilesystemCache that look like:

`isExpired(): <pathname>: TTL: xxx; last accessed: xxx; expired? xxx`

These should provide more info as to what FilesystemCache is seeing as it traverses through the directory tree and decides what to delete.

I don't know what inode limit you are running into, but I might also look into trying to increase that somehow, either by reformatting, or choosing a different filesystem format, or something. The cache worker is not smart enough to reliably protect you from bumping into such a limit.

**Comment by Ra1phM** [comment]
Okay, this makes sense. Thank you a lot. The limit is quite low because it's a 20GB drive dedicated for the applications, caches and logs.
Right now, I automatically monitor the inode level every hour and call the purge API if it reaches 70%. 

Maybe it might be an idea to allow configuring the API verb used by the worker?

**Comment by adolski** [comment]
My sense is that your storage is underprovisioned, and the frequent full purging you are doing seems more like an emergency workaround for this problem than an optimal solution. I can't really think of why frequent full purges should ever be a part of normal day-to-day server administration.

I think it is fair to expect users to have enough inodes to accommodate even a very large sized cache. For example, one random server VM that I have access to currently has a 40 GB root filesystem with 23,400,510 free inodes.

**Comment by Ra1phM** [comment]
From what I see in the cache , the inode limit is reached due to all the empty cache directories not cleaned up by Cantaloupe. At that point, less than 30% of the storage is used.

For example:

```
ls -lart /var/cache/cantaloupe/source/91/6e/94
drwxr-x---  2 tomcat tomcat 4096 Jun 17 17:30 .
drwxr-x--- 12 tomcat tomcat 4096 Jun 29 09:35 ..
```

There are 257 directories in `source/`, And then, each one has again 257 directories, and many last level directories are then empty. The call to the Purge API properly removes all empty directories.

Last thing I can try is to reduce `FilesystemCache.dir.depth` from 3 (default) to 2 and see if this helps, since it will remove 1 level in the directory structure.

**Comment by adolski** [comment]
@Ra1phM, I'm going to close this issue because I don't see any problems here, at least not with Cantaloupe--of course there is a problem with your storage, but there is nothing I can do about that.
