### ISSUE TITLE
images loading with white tiles

### ISSUE THREAD

**Issue by kimpham54** [cantaloupe-project/cantaloupe#380]
What we're using: We are using UniversalViewer with Cantaloupe. 

Issue: We are experiencing an issue where images load incorrectly at particular zoom levels, specifically where entire images or tiles have dimensions of 1250 or 1500 but we've also seen cases where it's other dimensions.

I was able to reproduce this issue in another viewer,
https://mirador-dev.netlify.app/__tests__/integration/mirador/

https://specialcollections.du.edu/iiif/6dd9f14c-e6d6-4577-9276-d0d50e91ca20/manifest
https://specialcollections.du.edu/iiif/99fc7f6f-0883-4930-8460-25b3a00921a9/manifest

Steps to reproduce:
- Try the following links:
https://specialcollections.du.edu/object/6dd9f14c-e6d6-4577-9276-d0d50e91ca20
https://specialcollections.du.edu/object/99fc7f6f-0883-4930-8460-25b3a00921a9
https://specialcollections.du.edu/object/96f2493e-ce66-462e-a8f8-2699b25f1e39
https://specialcollections.du.edu/object/9604c399-627f-4ed6-9960-67f4a6478c86

- Zoom in and out to view the images

<img width="867" alt="Screen Shot 2020-06-11 at 9 01 12 AM" src="https://user-images.githubusercontent.com/2915770/84409335-27535800-abc2-11ea-950c-c3414298c499.png">
<img width="1095" alt="Screen Shot 2020-06-11 at 9 00 41 AM" src="https://user-images.githubusercontent.com/2915770/84409348-2a4e4880-abc2-11ea-860b-97daabd71071.png">

We noticed that there's a consistent range where the white parts in the image appear for instance for images where the dimensions of 1500 are affected the range is between 1251-1503
https://specialcollections.du.edu/cantaloupe/iiif/2/99fc7f6f-0883-4930-8460-25b3a00921a9/0,0,3000,1834/1500,/0/default.jpg

https://specialcollections.du.edu/cantaloupe/iiif/2/99fc7f6f-0883-4930-8460-25b3a00921a9/0,0,3000,1834/1250,/0/default.jpg
https://specialcollections.du.edu/cantaloupe/iiif/2/99fc7f6f-0883-4930-8460-25b3a00921a9/0,0,3000,1834/1251,/0/default.jpg
https://specialcollections.du.edu/cantaloupe/iiif/2/99fc7f6f-0883-4930-8460-25b3a00921a9/0,0,3000,1834/1503,/0/default.jpg
https://specialcollections.du.edu/cantaloupe/iiif/2/99fc7f6f-0883-4930-8460-25b3a00921a9/0,0,3000,1834/1504,/0/default.jpg

What we've tried:
Kakadu and OpenJpeg processors, restarting cantaloupe, different StreamStrategies, sourcing tiffs instead of JP2s (we use jp2s), removing cache, trying different iiif viewers.

**Comment by DiegoPino** [comment]
Hi @kimpham54,

Disclaimer: this may be not a 100% solution.

Which version of Cantaloupe are you running?

There was an open issue (now marked as fixed) that addressed a similar use case
https://github.com/cantaloupe-project/cantaloupe/issues/309. Maybe just an update can fix your problem.

Also, i need to research/search my notes (if i find them really) to see how i fixed a similar issue (Black tiles) but i remember having to tune the min tile size in the config options (lower it), specially when images had already tiles encoded (like the ones kakadu generates). I was running an older version of Cantaloupe, but making the number smaller helped me at least debug the issue to the multiple resolution JPEG2000.

My impression based on your info.json 
https://specialcollections.du.edu/cantaloupe/iiif/2/9604c399-627f-4ed6-9960-67f4a6478c86/info.json
is that the tile size could be a little large.

I have a few recent Cantaloupe Servers running, maybe i can test locally and see if i can reproduce.

**Comment by DiegoPino** [comment]
@kimpham54 quick update here:

So i tested this image
`https://specialcollections.du.edu/cantaloupe/iiif/2/9604c399-627f-4ed6-9960-67f4a6478c86/full/full,/0/default.jpg ` => Second half of the image in white

`https://specialcollections.du.edu/cantaloupe/iiif/2/9604c399-627f-4ed6-9960-67f4a6478c86/full/3000,/0/default.jpg`  => Second half of the image in white (3000 == full so Ok, same behavior)

`https://specialcollections.du.edu/cantaloupe/iiif/2/9604c399-627f-4ed6-9960-67f4a6478c86/full/2500,/0/default.jpg`  => Image is complete
`https://specialcollections.du.edu/cantaloupe/iiif/2/9604c399-627f-4ed6-9960-67f4a6478c86/full/1250,/0/default.jpg`  => Image is complete

So not an issue with region, but with how the final image is constructed internally. Via Tiles of sizes that can not provided.

Also
- You seem to be Cantaloupe  4.0 (Response Headers of the request say so)
- You are using Kakadu

Same error happens if i request a TIFF.

Question:
Can you share the original image so i can test it in my own server?

**Comment by kimpham54** [comment]
thanks Diego, of course it's you. sending you the jp2 generated by archivematica and the original tiff
[cantaloupe_whitetile.zip](https://github.com/cantaloupe-project/cantaloupe/files/4766531/cantaloupe_whitetile.zip)

yep, cantaloupe 4.1.5

ok, we'll look into changing the tilesize. thanks!

**Comment by DiegoPino** [comment]
@kimpham54 thanks for the assets!

No White blocks/tiles here (good news).  But, my tiles are set to 512 Pixels. Look down, test ground for you to explore.

## Here is the live config
 -https://github.com/esmero/archipelago-deployment/blob/8.x-1.0-beta3/persistent/iiifconfig/cantaloupe.properties#L99

Using Cantaloupe 4.1.5 
- https://github.com/esmero/archipelago-deployment/blob/8.x-1.0-beta3/docker-compose-nginx.yml#L69

## Testground
I got this quickly ingested in our playground (Metadata could be totally offset, promise will remove once test is done or even now if you want me to)

https://play.archipelago.nyc/do/3c04c06b-79ef-43a8-8035-0ba4ec961a6f

That Object has 3 Files, the original your JP2000, a re-saved JP2000 (simple via OSX Preview, is still kakadu internally (yeah) but EXIF will change and probaly not multi res) and the TIFF. All 3 showing in Mirador via a realtime processed IIIF Manifest (so can make changes or give you an account if you want to test options). I set max width to 3000 pixels but Mirador will anyway call /full/ so you should be able to see all resolutions. 

You can expand the "Raw Metadata" to see the EXIF and how i named the files.

You can copy and paste the full Manifest 3.0 (Mirador is feeding from that Version) from down there, bottom of the page as a long string.

but there are also a few direct endpoints:

- https://play.archipelago.nyc/do/3c04c06b-79ef-43a8-8035-0ba4ec961a6f/metadata/iiifmanifest/manifest.jsonld (this is version 3)
and version 2 (limited to 1200)
- https://play.archipelago.nyc/do/3c04c06b-79ef-43a8-8035-0ba4ec961a6f/metadata/iiifmanifestv2/manifest.jsonld

E.g is the endpoint for the tiff file (using the file names directly as IDs to make things easier)

https://play.archipelago.nyc/cantaloupe/iiif/2/1a7%2Fimage-e6157846-909d-4942-9c68-c36f1e6082db-b063-04-0037-00097-7690b846-e165-440b-9e82-647610080b86.tiff/full/full/0/default.jpg


Hope this helps with the debugging. Please test as much as you want and feel free to ask me for an account or change the manifests and hit the server as much as you need to.

**Comment by giancarlobi** [comment]
@kimpham54 finally I tested your JP2 also with cantaloupe 4.1.6 and all works well as you can see here: 
http://archipelago.byterfly.eu/node/41
Also, full (3000px) is ok without white band: 
http://archipelago.byterfly.eu/iiif-server/iiif/2/c9d%2Fimage-e6157846-764dbd67-7f52-4b5b-84f6-1c01b1130282.jp2/full/full/0/default.jpg

**Comment by kimpham54** [comment]
tried to change the tilesize, did not end up working. we will probably try to update to 4.1.6

**Comment by kimpham54** [comment]
update to 4.1.6 fixed the issue. thanks for your help @DiegoPino @giancarlobi !
