### ISSUE TITLE
Multipage TIFF

### ISSUE THREAD

**Issue by carlkesselman** [cantaloupe-project/cantaloupe#389]
Three questions that I have tried to figure out myself, but was unsuccessful:

1) Is there currently a way to refer to a specific page in a tiff file.
2) Does the java2dprocessor support tiff pyramids using the subifd mechanism?
3) I noticed that there is a PR for being able to read files using the open microscopy tools.  That would be incredibly useful for me so for planning purposes, I was wondering if there is intent to include this functionality.

Thanks,

Carl

**Comment by adolski** [comment]
Hi @carlkesselman,

1. No

2. I've never tried a pyramidal TIFF in which the images are contained in sub-IFDs. It depends on whether the GeoSolutions TIFF reader (used by Java2dProcessor) supports this. I assume not but you'd have to try to confirm.

3. I haven't had time to look at this, but I'll try to get to it when I can.
