### ISSUE TITLE
How to improve image quality for a JPEG when reduced the size

### ISSUE THREAD

**Issue by spandan** [cantaloupe-project/cantaloupe#394]
Hello, 

I have a 500 X 500 jpeg image and i am trying to get a 75 X 75 version of the image using cantaloupe image server. The quality of image is blur. Is there a way i can improve the quality? Please advise. Thank you.

URL used: http://localhost:8182/iiif/2/7e2065e7-d6c3-4936-9889-f3857d3ab322.jpg/full/75,75/0/default.jpg

![Capture](https://user-images.githubusercontent.com/702607/89897439-a5bd7d80-dba4-11ea-9d08-04c9aef1d936.JPG)
![Capture-500X500](https://user-images.githubusercontent.com/702607/89897526-c4bc0f80-dba4-11ea-924f-e7b11e853004.JPG)

**Comment by adolski** [comment]
Hi @spandan,

Try playing around with the `processor.downscale_filter` and/or `processor.sharpen` configuration keys.
