### ISSUE TITLE
cache - corrupt images - how to override cache per request?

### ISSUE THREAD

**Issue by hrvoj3e** [cantaloupe-project/cantaloupe#403]
Is it possible to clean or skip specific derivate from cache in one request?
Something like "skip cache for this request" or something similiar.

I have an image `https://iiif.service4/srv2/iiif/2/ste3a09cf7%2Fupload%2F8%2Fzl%2Fj9e%2F8zlj9es381vz.jpg/full/198,/0/default.jpg`

Both full image `/full/full/0/default.jpg` and all derivatives like `/full/198,/0/default.jpg` are corrupted.

My goal is to refresh both source and derivate cache because I am using HTTP provider and images on that provider are newer.
I do not want to purge the whole cache!

Would it be possible to request 
 - `/full/full/0/default.jpg?cache_skip=1` 
    - to skip cache and generate the image live
 - `/full/full/0/default.jpg?cache_purge=1`
   - to remove this image from cache

**Comment by hrvoj3e** [comment]
OK, for purging cache there is http api [PurgeItemFromCache](https://cantaloupe-project.github.io/manual/5.0/endpoints.html#PurgeItemFromCache)

But my question is still for overriding cache per request.
E.g. manifest is generated live and we could override cache by appending args to service urls.

**Comment by adolski** [comment]
In 4.1 you can bypass the cache using `?cache=false`.

In 5.0 you'll also be able to re-cache (skip the cache read but do the write) using `?cache=recache`.
