### ISSUE TITLE
How to achieve robust health-probes?

### ISSUE THREAD

**Issue by cars10w** [cantaloupe-project/cantaloupe#406]
Hi,

we are operating Cantaloupe in a Kubernetes environment and the /health (also tried /status) endpoint is used for the liveness-health-probe of the pod. Basically this works fine.

But if there is a lot of pressure on the IIIFv2 API and Cantaloupe has to retrieve a lot of image data from our http-source, the health-requests are queued (since all http worker threads are already running) and responded way too late.  The result is a restart of Cantaloupe's pod.

Is anyone else here dealing with such scenarios?   How are you using the /health endpoint when Cantaloupe is busy doing other things?

Thanks and best regards!

**Comment by hrvoj3e** [comment]
Having the same problem.
Health endpoint takes 4+ seconds to respond GREEN.

**Comment by adolski** [comment]
The health checker in 4.1 is probably way more thorough than it needs to be:

> 1. The processing pipeline is exercised using all known-working sources and processors. This also checks that the underlying storage is online and readable.
> 2. The read/write functionality of the current source cache and/or derivative cache is checked.

This could potentially be very expensive. I don't see why processors need to be involved at all. So I've pushed a commit (above) that removes that aspect of the check, for inclusion in 4.1.8.

In 5.0 there is a new config key, `health.dependency_check`, that controls whether or not the health check performs checks of dependent sources & caches. Omitting these will greatly speed up the overall health check. In 4.1 you can temporarily achieve the same result as `health.dependency_check = false` by using `/` as your health check endpoint.

This all should be enough to alleviate any health check performance problems.
