### ISSUE TITLE
Using Cantaloupe with the IIIF Authentication API

### ISSUE THREAD

**Issue by hamza-anaphore** [cantaloupe-project/cantaloupe#417]
I am looking at implementing the **IIIF Authentication API**. Do you have any thoughts/advice on integrating **Cantaloupe** with the Authentication API ? 

Thank you in advance

**Comment by adolski** [comment]
There is some documentation on this topic here: https://cantaloupe-project.github.io/manual/4.1/access-control.html#IIIF%20Authentication%20API

**Comment by hamza-anaphore** [comment]
Thanks for your response and i appreciate all work you do, i am already read the documentation and i also do too much research about it but i need to know how i can link between IIIF Auth API and Cantaloupe ? and where i can create the JRuby files ?

by the way i work with [Mirador](https://github.com/ProjectMirador/mirador), Mirador its a viewer for manipulating images ([here is the Demo](https://mirador-dev.netlify.app/__tests__/integration/mirador/auth)), so what i wanna do is when a user want to see the images of a manifest in Mirador viewer he should authenticates because he don't have the permission to see the images before authentication, so there is an example with Stanford that do that but i don't have the permission to modify it, so for me i wanna do it with Cantaloupe not with Stanford, this is the example of the Stanforf manifest [here ](https://purl.stanford.edu/ds199xg9454/iiif/manifest), you can check it and see in service part : here is it 


 "service": [
                    {
                      "@context": "http://iiif.io/api/auth/1/context.json",
                      "id": "https://stacks.stanford.edu/auth/iiif",
                      "profile": "http://iiif.io/api/auth/1/login",
                      "label": "Log in to access all available features.",
                      "confirmLabel": "Login",
                      "failureHeader": "Unable to authenticate",
                      "failureDescription": "The authentication service cannot be reached. If your browser is configured to block pop-up windows, try allowing pop-up windows for this site before attempting to log in again.",
                      "service": [
                        {
                          "@id": "https://stacks.stanford.edu/image/iiif/token",
                          "profile": "http://iiif.io/api/auth/1/token"
                        },
                        {
                          "@id": "https://stacks.stanford.edu/Shibboleth.sso/Logout",
                          "profile": "http://iiif.io/api/auth/1/logout",
                          "label": "Logout"
                        }
                      ]
                    }
                  ]



in the id you see "https://stacks.stanford.edu/auth/iiif" , so here i wanna do it with Cantaloupe, Do you have any thoughts/advices to do it ?
If there is something not clear i can explain more


Thank you in advance

**Comment by cmhdave** [comment]
The manifest you linked to is a IIIF Presentation API manifest which is separate than what Cantaloupe provides functionality for (the IIIF Image API).  What Cantaloupe provides is the ability to authorize images based on a [HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) that would come in from the request after the authorization has already taken place.  Essentially what Mirador is doing is reading a Presentation API manifest which has a defined Authorization service.  Once the user is authorized, the image will attempt to be loaded from Cantaloupe with the HTTP Authorization header.

1. Mirador loads IIIF Presentation manifest
2. Mirador see Authorization block in manifest and authorizes the user through the defined service
3. Mirador passes authentication token to Cantaloupe via an HTTP Header
4. Cantaloupe takes the token from the HTTP header and processes it in the `authorize()` method in the delegates.rb file
5. Based on the boolean response from that delegate method it displays (or doesn't) the image.

**Comment by hamza0002** [comment]
@cmhdave  Thanks for your response and i appreciate all work you do, 

if you see this [demo ](https://mirador-dev.netlify.app/__tests__/integration/mirador/auth) you will be seen there is a manifest that asking tout login to continue to discover the images, and when you click the login button a popup window displayed so this is what i want to do with Cantaloupe, if you have any idea how i can do this popup window but with Cantaloupe, not other services,  the examples in the [demo ](https://mirador-dev.netlify.app/__tests__/integration/mirador/auth) each manifest have a service and when you click in the login button you will see the login form of this service, for example, Stanford that have a login form displayed when you click the login button, for me i need to do it my own login form not with any other service, i hope you understand me and thank you soo much for your help,
i didn't find responses for those questions so if you can give me some advices  
i need to know how i can link between IIIF Auth API and Cantaloupe ? 
and where i can create the delegates.rb file ?

Thank you in advance

**Comment by cmhdave** [comment]
As I mentioned Cantaloupe cannot handle the IIIF authentication part.  If you look at one of the defined manifests in the demo [https://iiifauth.digtest.co.uk/img/01_Icarus_Breughel.jpg/info.json](https://iiifauth.digtest.co.uk/img/01_Icarus_Breughel.jpg/info.json) you can see the authentication block

```
  "service": {
    "@context": "http://iiif.io/api/auth/1/context.json", 
    "@id": "https://iiifauth.digtest.co.uk/auth/cookie/login/01_Icarus_Breughel.jpg", 
    "confirmLabel": "Login", 
    "description": "Example Institution requires that you log in with your example account to view this content.", 
    "failureDescription": "<a href=\"http://example.org/policy\">Access Policy</a>", 
    "failureHeader": "Authentication Failed", 
    "header": "Please Log In", 
    "label": "Login to Example Institution", 
    "profile": "http://iiif.io/api/auth/1/login", 
    "service": [
      {
        "@id": "https://iiifauth.digtest.co.uk/auth/token/login/01_Icarus_Breughel.jpg", 
        "profile": "http://iiif.io/api/auth/1/token"
      }, 
      {
        "@id": "https://iiifauth.digtest.co.uk/auth/logout/login/01_Icarus_Breughel.jpg", 
        "label": "log out", 
        "profile": "http://iiif.io/api/auth/1/logout"
      }
    ]
  }
```
Mirador takes this information and renders the login box but the actual authentication is provided by `/auth/cookie/login`

**Comment by hamza0002** [comment]
@cmhdave thank you so much for your response and I appreciate it, 

I understand what you want to tell me, I know Cantaloupe is an image server he doesn't handle the IIIF authentication part, why I said that I want to do it with Cantaloupe because as you have seen here: https://iiifauth.digtest.co.uk/img/01_Icarus_Breughel.jpg/info.json , in the service part there an id of the login, this is what I am said to myself: if we can change the login of a manifest to my own login form and after that, the user is connected the manifest will take the images of the manifest from Cantaloupe image server because the examples in [the demo of mirador](https://mirador-dev.netlify.app/__tests__/integration/mirador/auth) each manifest has he's own service and own server image, so if we can change or do our login form to a manifest we can take the images of a manifest from our Cantaloupe image server and displayed those images to the user after he authenticates.
So this is exactly what i want to do, do my own login form after the user clicks the login button my popup windows will be displayed after that the user will be submitting the form, after that Cantaloupe takes the token from the HTTP header and processes it in the authorize() method in the delegates.rb file then will display the images based on the boolean response from the delegate method.


Thank you in advance

**Comment by cmhdave** [comment]
Yes, if you have an authentication service in place the token that is provided by that service can then be verified by Cantaloupe as described in this [documentation link](https://cantaloupe-project.github.io/manual/5.0/access-control.html#IIIF%20Authentication%20API). Basically your delegates.rb file would grab the token from the header, authenticate the token against your authorization service and return "true" if valid.  That would allow Cantaloupe to then display the image.  The magic all happens in `pre_authorize` and `authorize` depending on how much information you want made available.

**Comment by hamza0002** [comment]
@cmhdave thank you for your response and I appreciate it,

I have already seen this [documentation ](https://cantaloupe-project.github.io/manual/5.0/access-control.html#IIIF%20Authentication%20API) and I understood how it works, just if you have any idea about how I can do the link between the delegates.rb and submitted form, in another way how i can link the delegates.rb to my login form, that's means when a user clicks the login form how I can tell the systéme how to send the token? and how to go to verify the boolean response is it true or false and display the images to the user based on this response  
this is the schema (image below) of the work i was started, the question that asked here is about step 5 & 8 ( Mirador - Auth - Cantaloupe )as you can see in the image below
![20201202_161200](https://user-images.githubusercontent.com/57706104/102718027-1e1c1400-42e6-11eb-9cf8-fc9d19ae4ca1.jpg)

Thank You in advance
