### ISSUE TITLE
scale_constraint off-by-one problem

### ISSUE THREAD

**Issue by andrewmccarthy** [cantaloupe-project/cantaloupe#418]
Cantaloupe 4.1.7:

I'm using `delegates.rb` as described in the docs to set the `scale_constraint` limit to 1/2.

The original image is 4905×6788, and the constrained info.json gives the largest image as 2453×3394. However, if I try to download the full area in that size I get error "403 Access denied for the requested scale." I can, though, download 2452×3394.

It looks to me like one part of Cantaloupe is rounding 2452.5 up, while the other rounds down.

Thanks!

**Comment by adolski** [comment]
Hi @andrewmccarthy, thanks for reporting this. It is now fixed on the `release/4.1` branch, for inclusion in 4.1.8.
