### ISSUE TITLE
Watch of Configuration Files don't work

### ISSUE THREAD

**Issue by gjaekel** [cantaloupe-project/cantaloupe#427]
The watching of configuration files don't work as expected. It only get noticed of changes on a direct write of the file, but not at any other changes like touch or replacement (e.g. by renaming).

**Comment by adolski** [comment]
This sounds right to me. A hash of the contents of the file is stored in memory. When the JVM receives a file-changed event, a hash of the new contents is compared to the old contents, and the file is reloaded only if the hashes don't match. A touch or rename wouldn't change the file contents, so wouldn't trigger a reload.

**Comment by gjaekel** [comment]
Thank you for your help! This is `cantalope-4.1.7.war` running on a `WildFly-13` using `Adopt-OpenJDK-8u275`.

The described above was a try to figure out what might work and what not. The concrete error is: The directory with the configuration file is accessible by WebDAV, too. We're currently evaluating Cantaloupe and just **because** Cantaloupe offers this live-configuration feature, the configuration should be editable by the expert users at Evaluation stage. They also have WebDAV access to a image directory to self-provide objects to be used as test cases.

If I edit the configuration file via the command line at he running host, the change is detected and noted in the log:
```
20210111-100659.920 INFO  [work-lo-8695321] [{}] [stdout] Loading config file: /data/var/lib/wildfly/work/./cantaloupe/cantaloupe.properties.test

```
If it is edited by WebDAV, the change isn't recognised. But the file is changed as I can see by listing the content at command line.

As a testcase of this issue, we changed the presence of the V1 endpoint by toggling a comment:
```
[...]
# Enables the IIIF Image API 1.x endpoint, at /iiif/1.
# endpoint.iiif.1.enabled = false
endpoint.iiif.1.enabled = true
[...]
```
First, the file is edited remote via WebDAV -> nothing happens.
Second, the file is null-edited (read and write) via `vi` -> the change is recognized.

**Comment by gjaekel** [comment]
Additional information: I just figured out that the same issue happens if the config file is on a shared filesystem (here NFS) and it's changed from another host. Actually **all** our filesystems are attached via NFS to the applications (using Lightweight Linux Containers aka LXC). Therefore, the core issue might be that you don't get a notification event if the file isn't changed via the local VFS layer.

**Comment by adolski** [comment]
You probably figured it out. I think there is not much else that Cantaloupe can do other than poll the file, which I'd rather not do.

Config file watching is meant as a basic convenience for being able to tweak certain settings without having to restart. I don't think I would recommend allowing multiple users to edit the same file concurrently. This use case is probably beyond the scope of what the feature is intended to support.

**Comment by gjaekel** [comment]
This also happen if this configuration file is shared by two instances of Cantalope. This is quite common in our HA setup, where an application is deployed on at least two different computing nodes with and instances of an application server.

**Comment by adolski** [comment]
I will add a disclaimer about this feature to the user manual. Other than that I can only reiterate my previous comment.
