### ISSUE TITLE
When using the shaded version of cantaloupe.jar, JBIG and JP2 images in a PDF do not render

### ISSUE THREAD

**Issue by cmhdave** [cantaloupe-project/cantaloupe#428]
We've found that when you have a PDF with embedded images that were encoded with JBIG or with JP2, the shaded cantaloupe.jar can't find the `org.apache.pdfbox:jbig2-imageio` library.  Similarly we can't get `jai-imageio-jpeg2000` to work in the PDFs.  I _am_ able to get them to work by adding the jars independently to the classpath on startup like so
```
-cp jai-imageio-core.jar:jai-imageio-jpeg2000.jar:jbig2-imageio.jar:delegate.jar:cantaloupe.jar
```
Attached is a PDF you can test with.
[index.pdf](https://github.com/cantaloupe-project/cantaloupe/files/5803039/index.pdf)

**Comment by cmhdave** [comment]
Adding this here on how to add plugins to a JAR 

https://docs.oracle.com/javase/8/docs/technotes/guides/imageio/spec/extending.fm2.html

I just don't want to lose it.  I'll take a look at how it might be done during a build process when creating the shaded jar

**Comment by cmhdave** [comment]
Ah, I understand the issue now.  The `jbig2-imageio` library comes with a file in `META-INF/services` in the jar called `META-INF/services/javax.imageio.spi.ImageReaderSpi` but you would potentially have many of those based on the different plugins that implement that interface.  Hence including multiple ImageIO plugins in a shaded JAR presents a problem.  

This similar [issue](https://github.com/jai-imageio/jai-imageio-core/issues/29) opened on the jai-imageio project suggests that the Maven Shade plugin should handle this but you have explicitly defined `<exclude>META-INF/services/javax.imageio.*</exclude>`.  Were there other issues present when this wasn't explicitly excluded?

**Comment by adolski** [comment]
This must have got broken in the war-to-jar switch. I don't remember why the `javax.imageio.*` services were being excluded. It should be fixed now, and hopefully the fix didn't break something else.
