### ISSUE TITLE
Upload Image via HTTP request

### ISSUE THREAD

**Issue by BalduinLandolt** [cantaloupe-project/cantaloupe#430]
I have a simple setup where Cantaloupe hosts images from a folder in the file system.

What I would like to do is to allow authenticated users to upload files to said file system folder via HTTP request to Cantaloupe's HTTP endpoint API.

Is that already possible by any chance? And if so, how?  
And if not, could that be a feature to consider?

**Comment by adolski** [comment]
Hi @BalduinLandolt,

Uploads are not a planned feature and not a direction we want to go. This is because of limited resources on the project, and also, wanting to avoid scope creep.

**Comment by BalduinLandolt** [comment]
Too bad, but fair enough. In that case, feel free to close the issue. :)
