### ISSUE TITLE
PDFBox loads entire PDF into memory to render single page

### ISSUE THREAD

**Issue by cmhdave** [cantaloupe-project/cantaloupe#432]
We have found that some extremely large PDFs (think over 1GB) can very quickly exhaust all server memory resources if multiple requests come in for different pages of the same PDF.  For example if you create a presentation manifest with a separate entry for each page of the PDF, in something like Mirador you would render multiple pages at once and quickly gobble up many multiple GB as it loads the entire PDF into memory for EACH page.

PDFBox as implemented in Cantaloupe's PdfBoxProcessor calls `PDDocument.load()` with a single parameter, either the file or an input stream.  PDFBox has the ability to also tell it how to use memory:
```
PDDocument load(File file, MemoryUsageSetting memUsageSetting)
```
or
```
PDDocument load(InputStream input, MemoryUsageSetting memUsageSetting)
```
`MemoryUsageSetting` allows you to set these properties to better control memory consumption
```
    private final boolean useMainMemory;
    private final boolean useTempFile;
    private final long maxMainMemoryBytes;
    private final long maxStorageBytes;
    private File tempDir;
```
I feel it has become critical for us to be able to control these settings via Cantaloupe configuration.  Something like this 

```
MemoryUsageSetting settings = MemoryUsageSetting.setupMixed(maxMemoryBytes).setTempDir(pdfTempDir);
doc = PDDocument.load(sourceFile.toFile(), settings);
```

I could take a swing at a PR. Or if you want to address it I'll stand back.  I just don't want to duplicate effort.

**Comment by adolski** [comment]
Hi @cmhdave,

This seems like a reasonable configuration to add but I'm not sure how exactly it would work. Would PDFBox prefer to use memory, but then dump the decoded PDF structure to disk when the PDDocument size exceeds `maxMainMemoryBytes`?

I also wonder how you would tune `maxMainMemoryBytes`.

Is there much of a performance difference between memory & disk?

Another thing that might improve efficiency, aside from this, might be to share a PDDocument instance across threads, when there are multiple simultaneous requests for the same PDF. (I assume that PDDocument allows thread-safe reading?)

So, yeah, it sounds like a useful feature to be able to control memory usage in this way, but I'm not sure how it would work and I don't really have time to implement it in the near term.

**Comment by cmhdave** [comment]
First I'll answer the question about sharing a PDDocument across threads, from the PDFBox FAQ:

> Is PDFBox thread safe?
> 
> No! Only one thread may access a single document at a time. You can have multiple threads each accessing their own PDDocument object.

This is actually how we identified the issue.  A heap dump from the JVM showed multiple pages from the same 1.7GB PDF loaded in memory multiple times.  It loads the same PDF in memory for each page.

To answer the question of how it's done you have to look at the documentation for the ScratchFile in PDFBox.

https://pdfbox.apache.org/docs/2.0.13/javadocs/org/apache/pdfbox/io/ScratchFile.html

> Implements a memory page handling mechanism as base for creating (multiple) RandomAccess buffers each having its set of pages (implemented by ScratchFileBuffer). A buffer is created calling createBuffer().
> 
> Pages can be stored in main memory or in a temporary file. A mixed mode is supported storing a certain amount of pages in memory and only the additional ones in temporary file (defined by maximum main memory to be used).
>
> Pages can be marked as 'free' in order to re-use them. For in-memory pages this will release the used memory while for pages in temporary file this simply marks the area as free to re-use.
> 
> If a temporary file was created (done with the first page to be stored in temporary file) it is deleted when close() is called.
>
> Using this class for RandomAccess buffers allows for a direct control on the maximum memory usage and allows processing large files for which we otherwise would get an OutOfMemoryError in case of using RandomAccessBuffer.
>
> This base class for providing pages is thread safe (the buffer implementations are not).

**Comment by cmhdave** [comment]
I do have a resolution for this in my fork but I'd like to do some more testing with it before I open a PR.  In particular I want to see what happens when the allocated memory is less than the full size of the PDF.

**Comment by cmhdave** [comment]
Ok, my testing is complete.  Overall the performance is much better now that the whole PDF isn't loaded into memory.  It's not as fast as if the images were JP2 to begin with but the sacrifice in speed is the balancing act.

The scenario I mentioned above where the "maxStorageBytes" is set to more than the size of the PDF results in the following 500 error:
```
java.io.IOException: Maximum allowed scratch file memory exceeded.
	at org.apache.pdfbox.io.ScratchFile.getNewPage(ScratchFile.java:172)
	at org.apache.pdfbox.io.ScratchFileBuffer.addPage(ScratchFileBuffer.java:126)
	at org.apache.pdfbox.io.ScratchFileBuffer.ensureAvailableBytesInPage(ScratchFileBuffer.java:184)
	at org.apache.pdfbox.io.ScratchFileBuffer.write(ScratchFileBuffer.java:236)
```

I think that's an appropriate outcome if you restrict both memory and disk storage usage.  This might be something that a user might deem necessary if they are restricted on memory and disk space usage.  Otherwise restricting memory and giving maxStorageBytes unlimited storage results in actual responses rather than heap dumps and OutOfMemory exceptions.
