### ISSUE TITLE
Overlay image covers base image, not blended into

### ISSUE THREAD

**Issue by mitring** [cantaloupe-project/cantaloupe#433]
Documentation section [about overlays](https://cantaloupe-project.github.io/manual/4.1/overlays.html) says that

> An image overlay must be a 24-bit RGB or RGBA PNG image. **It will be blended pixel-for-pixel into the output image.**

Example picture named "Repeating image overlay" shows such behavior. But actually overlay image simply covers base image without transparency, making it impossible to create watermarks.

As I can see in [source code](https://github.com/cantaloupe-project/cantaloupe/blob/79e910f5a57f5c0c8db30b64fb7005999fead456/src/main/java/edu/illinois/library/cantaloupe/processor/Java2DUtil.java#L383-L403) of `edu.illinois.library.cantaloupe.processor.Java2DUtil` class, such behavior is not surprising: overlay image is drawn over base image without settings for blending.

Initialization of `Graphics2D` for blending must be something like this:
```java
final Graphics2D g2d = baseImage.createGraphics();
g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER).derive(0.5f));
```

Perhaps such initialization should be conditional based on settings in properties file.

**Comment by adolski** [comment]
Hi @mitring, does your overlay image have alpha transparency?

**Comment by mitring** [comment]
Hi @adolski, I try to create watermark with sample overlay [image](https://cantaloupe-project.github.io/manual/4.1/images/overlay-sample.png) mentioned in documentation. Now I see that watermarking requires alpha transparency in overlay image.

So nothing wrong with the source code, but there is some confusing inaccuracy in ["Overlay" section](https://cantaloupe-project.github.io/manual/4.1/overlays.html) of documentation: the behavior shown in the picture named "Repeating image overlay" is impossible to achieve with sample overlay image.

**Comment by adolski** [comment]
I see what you mean. I'll make a note to fix that.
