### ISSUE TITLE
Pyramidal tif to jpeg error

### ISSUE THREAD

**Issue by bingaman** [cantaloupe-project/cantaloupe#435]
Trying to create a JPEG derivative from the following ptif:
https://github.com/bingaman/sample-tifs/blob/master/77951d0c-d781-eac6-f4ff-f13cc5cfc0cf.tif?raw=true

Any request for a derivative smaller than the second-largest pyramid works, any request for a derivative from the largest pyramid fails with the following error in application.log:
2021-02-08 11:10:42,319 INFO [qtp434176574-327] e.i.l.c.r.ErrorResource [AbstractResource.java:117] Handling GET /iiif/2/77951d0c-d781-eac6-f4ff-f13cc5cfc0cf/full/!2924,2924/0/default.jpg

/iiif/2/77951d0c-d781-eac6-f4ff-f13cc5cfc0cf/full/!2923,2923/0/default.jpg works without a problem.

I can't see anything wrong with the ptif itself, using imagemagick I can convert the larger pyramid to jpeg without a problem.

**Comment by adolski** [comment]
I can't reproduce the error with the `!2924,2924` request. It loads slowly, but it does load for me (in 4.1.7). Are you sure there is no more information logged than that?

**Comment by bingaman** [comment]
That's everything in the application log. How slowly does it load for you? That was enough of a clue though...I think we're hitting a  proxy timeout here.

**Comment by bingaman** [comment]
Here is another sample, haven't been able to get a /full/!3000,3000 back out from this one, even with the timeout set to 5 minutes:

https://github.com/bingaman/sample-tifs/blob/master/c313fc5a-bbba-ce20-6bbe-d077780dfb42.tif?raw=true

**Comment by bingaman** [comment]
Marking as closed as this is probably an issue with our system not cantaloupe.
