### ISSUE TITLE
Multipage Tif as source document(s)

### ISSUE THREAD

**Issue by jten10** [cantaloupe-project/cantaloupe#440]
We have > 25,000 multipage tifs. in fax4 format.  Some were originally microfilms and the conversion was done to multipage tif.  The largest files have over 10,000 images and approx 350megs.  Can Cantaloupe read these? and can it send the pages to an IIP client like seadragon?  I am looking for an open source image server/client combo that can handle this.  Thanks.

**Comment by adolski** [comment]
Hi @jten10,

Multi-page TIFFs aren't currently supported, but I'm interested in adding support. I think it would be relatively simple to do.

Are you able to share a sample file from this collection?

**Comment by jten10** [comment]
Yes, I have a test file I use.  It is not very large (9 pages).  How should I provide it?

**Comment by adolski** [comment]
You should be able to drag & drop it into the comment box.

**Comment by jten10** [comment]
Here's the sample file.

[0F04D6BF-04FB-4367-A375-7B165D7B7F17.zip](https://github.com/cantaloupe-project/cantaloupe/files/6039021/0F04D6BF-04FB-4367-A375-7B165D7B7F17.zip)

**Comment by adolski** [comment]
Thanks, I'll keep you posted.

**Comment by jten10** [comment]
Thanks

**Comment by adolski** [comment]
This is working now on the `develop` branch for inclusion in 5.0. Here's how it works: https://cantaloupe-project.github.io/manual/5.0/images.html#Multi-Page%20Images
