### ISSUE TITLE
Upscaling the native dimensions in info.json.

### ISSUE THREAD

**Issue by qudratullah1061** [cantaloupe-project/cantaloupe#442]
Hi,

I want to know that is there any existing feature that cantaloupe offer to resize low resolution images to high resolution like iiifhosting.com is doing?

For example, if I have image of 1000x750 and upload it to directory. When i access with cantaloupe end point url like, 
{scheme}://{server}{/prefix}/{identifier}/info.json
https://example.org/image-service/abcd1234/info.json

I got width = 1000 and height = 750 of image in json response.

I want to increase that width and height of image to something like 6117x4112.

I am asking this because i am using mirador viewer in my web application and mirador viewer does not zoom in and zoom out low resolution images.

Before that i was using iiifhosting.com now i want to setup my own server. 

When i upload images on iiifhosting.com like i have uploaded 1000x750 image on iiifhosting.com and when i access image info.json 
{scheme}://{server}{/prefix}/{identifier}/info.json
it gives me width and height of image to higher scale like some greater values 6117x4112. Please let me know how i can achieve that.

Thanks.

**Comment by adolski** [comment]
Hi @qudratullah1061 ,

Cantaloupe always supplies the native dimensions in the `info.json`. The client needs to request the desired scale using IIIF Image API syntax.

**Comment by qudratullah1061** [comment]
I have uploaded an image on iiifhosting.com of 2000x1000 and when i get info.json i got width: 11658, height: 6112. Check this url.

http://bafdev.iiifhosting.com/iiif//e6ebb551407a5c64903d100ab8ba9199bb264d1c17cdcf0a9e745cd6c5aea432/info.json

When i try to get full image with api and downloads it, its just only 1000x524

http://bafdev.iiifhosting.com/iiif//e6ebb551407a5c64903d100ab8ba9199bb264d1c17cdcf0a9e745cd6c5aea432/full/full/0/default.jpg

I want to know how iiifhosting doing this? Any clue? Is it storing two seperate images? How we are accessing same image with different res? In info.json its width and height is different and when i download with second url dimensions are different. Please help.

Thanks.

**Comment by adolski** [comment]
I don't know anything about iiifhosting.com or how it works. You would have to contact them.

**Comment by qudratullah1061** [comment]
Thanks for your answers. Really appreciated.

One more thing can you please tell me, If I have an image of 500x500 and access image info.json via url {scheme}://{server}{/prefix}/{identifier}/info.json i got width = 500 and height = 500 as in original image.

How can I get info.json with width = 2000 and height = 2000 or some higher number?


Basically i am using mirador viewer and if my image is low resolution like 500x500 image and mirador viewer reads info.json file in which it gets width = 500 and height = 500 it does not zoom in and zoom out image. On the other hand if i have image with resolution 5000x5000 (high resolutioin) it gets width and height of 5000x5000 in info.json and works fine. So basically i want to change values in info.json so mirador viewer can zoom in and zoom out my low resolution images.

Please let me know if i am not clear to you.

Many thanks.

**Comment by adolski** [comment]
Cantaloupe will always deliver the native image dimensions in the `info.json`. There is no way to get it to deliver larger ones. Instead, the client (Mirador in your case) must request the size that it wants to display. If it wants to enlarge a 500x500 image to 2000x2000, it needs to request a 2000x2000 image using a URL like:

`{scheme}://{server}/iiif/2/{identifier}/full/!2000,2000/0/default.jpg`

(See https://iiif.io/api/image/2.1/#size)

(In Cantaloupe's default configuration file, `max_scale` is set to 1.0, so you'd have to increase that.)

I don't know if Mirador has some kind of configuration option for auto-enlarging small images... If not, you would have to pursue this issue with the Mirador project.
