### ISSUE TITLE
Cantaloupe pyramids

### ISSUE THREAD

**Issue by qudratullah1061** [cantaloupe-project/cantaloupe#444]
Hi,

I have setup image server and some test images. My question is how image server builds sizes array in info.json and where these pyramids are stored?  Screenshot attached below.

http://prntscr.com/10cxh3x

Look at this url. http://baf-website4-dev.itcomrade.us/iiif/fbbd6ca4ab80a3153c8ef3e2cbe060566e2d408fe2e6d1015bdf67c2d8c8e3c9/info.json

If cantaloupe image server generates these sizes on the fly than how can I pre generate them to increase performance. Like if i have image of 5000x5000 and i need thumbnail of 200x200 then image server do it on the fly. What if i pre-generate these sizes and serve them? How can i increase performance or best method to serve image if I have images more than 70,000. Please help.

Thanks.

**Comment by adolski** [comment]
Hi,

> I have setup image server and some test images. My question is how image server builds sizes array in info.json and where these pyramids are stored? Screenshot attached below.

How the sizes and tiles arrays are calculated is explained here: https://cantaloupe-project.github.io/manual/4.1/endpoints.html#IIIFImageAPI2

> If cantaloupe image server generates these sizes on the fly than how can I pre generate them to increase performance. Like if i have image of 5000x5000 and i need thumbnail of 200x200 then image server do it on the fly. What if i pre-generate these sizes and serve them? How can i increase performance or best method to serve image if I have images more than 70,000. Please help.

Cantaloupe doesn't know what images you are serving nor what sizes clients are going to request. Clients are not restricted to the sizes in the `sizes` array (unless `endpoint.iiif.restrict_to_sizes = true`) nor the tile sizes. So Cantaloupe has no way of knowing what to pre-generate.

This is why it's recommended to use images in formats that can be read efficiently at large sizes or small scales, like JPEG2000 or pyramidal tiled TIFF: https://cantaloupe-project.github.io/manual/4.1/images.html#Source%20Formats If the image format is efficient enough to read, there is little or no performance benefit to pre-generating.

Another good idea is to turn on the derivative cache, or set up some other front-end cache, that will store the images that get generated. This way, only the first request for a particular image URL will have any significant cost.

**Comment by qudratullah1061** [comment]
Thank you very much for your answer. Its really helpful. Thanks again.
