### ISSUE TITLE
Without delegates.rb enabled an error requesting info.json in 5.0-SNAPSHOT

### ISSUE THREAD

**Issue by giancarlobi** [cantaloupe-project/cantaloupe#445]
@adolski I compiled branch develop and run it as standalone 5.0-SNAPSHOT. Local images are rendered well. When I request an info.json I receive this error: 
500 Internal Server Error
If a request context is set, a delegate proxy must also be set.
Enabling delegates.rb (rename the original one) without any changes then info.json request works.
I check with both commands to run server (java -cp ... and java --- -jar...) the same issue in both cases.
Also, this happens with and without reverse proxy.
Any ideas or more checks?
Thanks

**Comment by adolski** [comment]
Thanks for the heads-up @giancarlobi , this is fixed now.

**Comment by giancarlobi** [comment]
@adolski Thanks to you for quick response/repair.
