### ISSUE TITLE
Question: Calculating possible HEAP usage based on width and height

### ISSUE THREAD

**Issue by DiegoPino** [cantaloupe-project/cantaloupe#447]
Hello, this is really a question and not a feature request.

In our system we are trying to avoid Java Heap (Out of memory errors) for very large images based on an upfront estimate of possible memory usage based on the `info.json` response, the available sizes plus EXIF/identify data extracted locally available before we build the Image API url.

Our test case: Archipelago Docker base deployments (https://github.com/esmero/archipelago-deployment, Development machines running locally, very small servers): `XMX=2G` for Cantaloupe 4.1.7 and using Java2D/TurboJpeg (both acting the same re: Memory usage) processors for JPEG.

Testing with a very large image (NASA, Perseverance) we get this info.json

```JSON
{
  "@context": "http://iiif.io/api/image/2/context.json",
  "@id": "http://localhost:8183/iiif/2/9ff%2Fimage-9ff-image-pia2464-perseverance-sol3-mastcam-z-panorama-400ec5b1-fdf2-4d56-8c5c-99f36553984a-7022cf8e-878a-482a-ab09-ee3708e16e7b.jpg",
  "protocol": "http://iiif.io/api/image",
  "width": 36952,
  "height": 11570,
  "sizes": [
    {
      "width": 289,
      "height": 90
    },
    {
      "width": 577,
      "height": 181
    },
    {
      "width": 1155,
      "height": 362
    },
    {
      "width": 2310,
      "height": 723
    },
    {
      "width": 4619,
      "height": 1446
    },
    {
      "width": 9238,
      "height": 2893
    },
    {
      "width": 18476,
      "height": 5785
    }
  ],
  "tiles": [
    {
      "width": 512,
      "height": 512,
      "scaleFactors": [
        1,
        2,
        4,
        8,
        16,
        32,
        64,
        128
      ]
    }
  ],
  "profile": [
    "http://iiif.io/api/image/2/level2.json",
    {
      "formats": [
        "jpg",
        "tif",
        "gif",
        "png"
      ],
      "maxArea": 400000000,
      "qualities": [
        "bitonal",
        "default",
        "gray",
        "color"
      ],
      "supports": [
        "regionByPx",
        "sizeByW",
        "sizeByWhListed",
        "cors",
        "regionSquare",
        "sizeByDistortedWh",
        "canonicalLinkHeader",
        "sizeByConfinedWh",
        "sizeByPct",
        "jsonldMediaType",
        "regionByPct",
        "rotationArbitrary",
        "sizeByH",
        "baseUriRedirect",
        "rotationBy90s",
        "profileLinkHeader",
        "sizeByForcedWh",
        "sizeByWh",
        "mirroring"
      ]
    }
  ]
}
````

Aa very simple memory calculation (and please correct me, I could be wrong)

`height x width * 16 (Color depth) * 3 (Channels) / 8 / 1024 / 1024)`  give us, for this image, `2445 Mbytes`

For testing we set ourself a soft limit of 768Mbytes, so we keep iterating over the available `sizes` pairs until we find a size pair that works. Issue is our naive estimates do not work.

So. What we try here to establish is the conservative soft limit that works for a given XMX (approximate, because of course it will depend on how many requests we get, load, etc). Our tests show that a request for:

`/full/16384,/0/default.jpg` (in this case we decide to fall back even lower than 18476x5785 because of an extra constraint webGL Max texture size), gives us immediately a

```
500 Internal Server Error
Java heap space

java.lang.OutOfMemoryError: Java heap space
```

And this is what the Admin interface shows as HEAP Usage 
![Screen Shot 2021-03-07 at 3 40 39 PM](https://user-images.githubusercontent.com/6946023/110254067-7d8bd680-7f5b-11eb-98a4-7f56e76314d2.png)

So, I'm concluding that 768Mbytes of actual Pixel/Color Depth usage is actually using ~2.5x the Java Heap ? (38Mbytes o Heap Used before the request). Is that accurate? Anyone knows about a better/more accurate HEAP v/s Space in memory calculation for an image based on Cantaloupe's Java2D implementation?

Of course a call directly to /max/ delivers without memory issues because there is no scale down happening, but because we have also webGL constraints and we would like in general avoid calling un-processable sizes for IIIF image, we would love to hear your opinion on this.

_Another note_: switching to graphics magic immediately removes the HEAP errors because we compiled it with Q8 (which lowers the color depth and also because in case of running out of memory it will use FileSystem and of course does not run inside the JVM. But its also quite slow.

Any hints and mathematical corrections are welcome!

Thanks a lot

**Comment by adolski** [comment]
Hi @DiegoPino , here are just some random thoughts:

* In recent JVM versions, `-Xmx` is not necessary when running in Docker. The JVM should autodetect.

* I don't know if the size of a BufferedImage can be estimated with a simple formula like that. The BufferedImage's internal structure will vary and I'm sure there is some extra overhead (but I don't know how much). Maybe you could sample some real-world BufferedImages using e.g. a profiler or heap dump analyzer to get an idea. Also, there may be multiple BufferedImages generated through the processing pipeline, with possibly several remaining in memory at any given time, waiting to be GCed. Then there are concurrent requests to consider, with each one having its own pipeline.

* It's not necessary to use any of the dimensions in the `sizes` array unless `endpoint.iiif.restrict_to_sizes = true`. These are mostly just suggestions to increase the chances of cache hits, and using them doesn't otherwise confer much, if any, performance benefit.

* The `max_pixels` key may be helpful here.

**Comment by DiegoPino** [comment]
@adolski thanks a lot. I will do some debugging to understand better the Memory reality, my math there is quite naive. We only use info.json Sizes for a single use case (Panoramas) to avoid some calculations (cheap I know) and to avoid generating too many cacheable derivatives. This is really a lot about webGL too and having that limit, since a call to the full size image could be simpler in many cases.

I appreciate your insight and quick response as always.

**Comment by DiegoPino** [comment]
@adolski a housekeeping question for you. If the opener feels "happy" with the reply (like myself), do you prefer the Opener to close the issue? Or you prefer to keep questions open to avoid people asking the same many times? Just wondering what works better for you. Thanks a lot!

**Comment by adolski** [comment]
If the opener doesn't close a closeable issue, I'll get around to it eventually. It's not a big deal. Duplicate questions haven't been a problem so far.

GitHub recently deployed a new discussions feature, and I've started to try to gently steer questions over there from the website. I don't want to be strict about it, though.

**Comment by DiegoPino** [comment]
Thanks a lot. Closing this issue then!
