### ISSUE TITLE
Question: Restriction method to permit only calls from specific application eg UV

### ISSUE THREAD

**Issue by stephenmcconnachie** [cantaloupe-project/cantaloupe#448]
Do any of the access restriction methods at https://cantaloupe-project.github.io/manual/5.0/access-control.html support the aim of preventing Cantaloupe being called outside a specific viewer client - eg UV? We are using Cantaloupe and UV, and the aim would be to prevent Cantaloupe from responding to calls that don't originate in UV. This may be difficult without scripting, but looking for any options in Cantaloupe config itself, even if some scripting is required to use those Cantaloupe restrictions options.

**Comment by DiegoPino** [comment]
You can use some passed headers or a cookie and the `Delegate` methods (a ruby file) to do something like that, or even "obscure" your IDs with a prefix of some sort.

But IMHO it actually goes a bit against the whole magic of IIIF. If your IIIF Manifests can only be used in UV and only in your site, and then you are not using the something like https://iiif.io/api/auth/1.0/implementation/ to state that your resources are protected, it can be quite confusing for the outside world.

Also: headers and most of what is transmitted via HTTP can be tampered with, so having some type of session/cookie plus a service you can callback from the Delegate to validate it (e.g JWT) is something I would suggest if you are really going that way.

Docs here:
https://cantaloupe-project.github.io/manual/5.0/access-control.html#Delegate%20Methods

**Comment by stephenmcconnachie** [comment]
> You can use some passed headers or a cookie and the `Delegate` methods (a ruby file) to do something like that, or even "obscure" your IDs with a prefix of some sort.
> 
> But IMHO it actually goes a bit against the whole magic of IIIF. If your IIIF Manifests can only be used in UV and only in your site, and then you are not using the something like https://iiif.io/api/auth/1.0/implementation/ to state that your resources are protected, it can be quite confusing for the outside world.
> 
> Also: headers and most of what is transmitted via HTTP can be tampered with, so having some type of session/cookie plus a service you can callback from the Delegate to validate it (e.g JWT) is something I would suggest if you are really going that way.
> 
> Docs here:
> https://cantaloupe-project.github.io/manual/5.0/access-control.html#Delegate%20Methods

Thank you @DiegoPino
