### ISSUE TITLE
Prevent auto redirect to info.json

### ISSUE THREAD

**Issue by qudratullah1061** [cantaloupe-project/cantaloupe#456]
Hi,

Currently if user goes to http://servername/iiif/2/image.jpg server automatically redirects it to http://servername/iiif/2/image.jpg/info.json 

What if i want to show my custom html page, don't want to redirect to info.json by default?

Any help?

Thanks.

**Comment by adolski** [comment]
Hi,

That redirect is recommended by the IIIF Image API: https://iiif.io/api/image/2.1/#uri-syntax

> When the base URI is dereferenced, the interaction should result in the image information document. It is recommended that the response be a 303 status redirection to the image information document’s URI. Implementations may also exhibit other behavior for the base URI beyond the scope of this specification in response to HTTP request headers and methods.

So Cantaloupe does the redirect and there isn't any way to change that behavior.

**Comment by qudratullah1061** [comment]
Is there any method of delegate script which calls before redirection to info.json? Or any other way to check if user specified info.json in url or not?

**Comment by adolski** [comment]
Nope.

**Comment by qudratullah1061** [comment]
Alright. Thank you very much for your quick response and help. :)
