### ISSUE TITLE
Cantaloupe PurgeItemFromCache always returns 202

### ISSUE THREAD

**Issue by cachemeoutside** [cantaloupe-project/cantaloupe#458]
Hello again,

I've found that the PurgeItemFromCache API request always returns a 202 regardless of whether the ID exists or not. I guess I would expect a 404. Is this expected? Seems like we'll have to check against md5 hash of the ID in our cache to validate if the cache was cleared or not.

Thanks!

**Comment by DiegoPino** [comment]
@cachemeoutside yes, it is expected.

In the Docs:
`Expected Response | 202 Accepted with task URI in Location header`

HTTP 202 makes sense in this context, request is "passed" but it may not had any effect yet or may be processed later (means you do not need to wait / there is no commitment to a response). 404 would imply that the request needs to be validated during your call and the current implementation does not return anything back to the callable about that (there is logging about not found IDs and exception catching)

Normally APIs that respond with a 202 are of the "request and forget" type and may even be async (`purgeAsync`) 

https://github.com/cantaloupe-project/cantaloupe/blob/792f17575b42f711eb99d99875066134fa2c406e/src/main/java/edu/illinois/library/cantaloupe/cache/CacheFacade.java#L169

**Comment by DiegoPino** [comment]
@cachemeoutside I forgot something.

The request will return a location to a Task, which can be checked for completion. So maybe you can check that afterwards (as long as you did not restart the server) to be sure the request had the desired effect.

`
Invoking a POST /tasks request creates an asynchronous task identified by a UUID and submits it to a processing queue. Its status can be checked via GET /tasks/:uuid. Task records are retained in memory, but are not persisted, so checking a task after a restart will result in a 404 Not Found response.
`

**Comment by cachemeoutside** [comment]
Awesome. Thank you! Satisfied with the answer. Closing this issue.
