### ISSUE TITLE
Ability to limit the cache size

### ISSUE THREAD

**Issue by bcail** [cantaloupe-project/cantaloupe#463]
Thanks for your work on cantaloupe.

Our scenario is that we have a certain amount of space for the cache, and we need to purge content regularly to keep from filling it up. I see that we can use the cache worker to purge expired content, and we can use http api to purge either a whole cache or the cached content for one identifier.

Are there any other options? Seems like the api is great if we need to manually expire an item, but not for daily purging old cache content so that cache doesn't fill up - we don't know all the ids of the items in the cache, and might need to purge a lot of items. Purging the whole cache isn't great, because then we lose all the cached content that we could otherwise reuse.

The issue with the worker is that it works based on the expiration time of the content, not based on disk usage. So if we cache content for a month, and have 3 weeks of increased traffic, the worker wouldn't be purging any of the new content and the cache could fill up.

Am I missing anything with this analysis?

Would it be an option to run a script externally, to check disk usage and delete cache directories as needed? Would that cause problems for cantaloupe?

**Comment by adolski** [comment]
Hi @bcail ,

I guess it would be possible to add a feature like this, with the caveat that it would be hard to make it perfectly reliable. But so far, it's been easier for me to just ask users to increase their storage allocation, which I think is fair when they are intending to run a production service with only 10 GB or whatever small amount of space for the cache.

In the meantime, it should be fine to delete stuff via a script. You might rarely see some logged IOExceptions from FilesystemCache when content is moved/deleted underneath it, but nothing that would affect the integrity of the cached content.

**Comment by bcail** [comment]
ok, thanks.
