### ISSUE TITLE
Add ability to disable HEAD request on HttpSource

### ISSUE THREAD

**Issue by maksimkurb** [cantaloupe-project/cantaloupe#465]
Hello. I have scenario where images can be served from different locations, e.g. filesystem, multiple S3 (MinIO), GCP.

We have special microservice which is responsible to return direct URL to a file by it's identifier. For images that stored on filesystem it returns URL to itself (for proxying file download), but for S3 and GCP it returns [PreSigned URLs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html), so other services can download file directly from S3 without transferring it through file microservice.

There is one problem with PreSigned URLs in Cantaloupe: when image is required, Cantaloupe maked `HEAD` request to URL which is returned by delegate to ensure that image is exists and available. But PreSigned URLs return 403 Forbidden error code because they allow only `GET` requests. Cantaloupe does not has any property to forbid outcoming HEAD requests, but such option can solve problem with PreSigned URLs in our scenario. For a `HEAD` request replacement, Cantaloupe can use `GET` request with small `Range` to fetch image info such as `Content-Type` and `Content-Length` if needed.

It can be a global option for HttpSource or additional key to return value of `httpsource_resource_info` delegate could be added, what do you think?

**Comment by maksimkurb** [comment]
I have created a pull request which resolves my problem by adding a configuration switch, can you look into it, please?

**Comment by adolski** [comment]
Hi @maksimkurb, sorry for the delay.

HttpSource actually used to not use a HEAD request, but #233 changed this. Now it's clear that some servers will require a HEAD-first strategy whereas others (like yours) will require ranged GET.

I like your solution, but for more flexibility, I think I would like to make it work on a per-request basis which would mean adding:

1. A new config key, `HttpSource.BasicLookupStrategy.enable_head_requests` (not 100% sure on that name yet)
2. An `enable_head_request` key in the hash returned from `httpsource_resource_info()` (again not sure on name)

This will accommodate cases in which one source needs HEAD-first and another needs GET-first.

And it will be quite a bit more work than what you've done in #467, but I'm happy to do it, although it will take a while.

**Comment by maksimkurb** [comment]
Hi, thank you for your answer. Yes, solution with delegates will be more flexible for sure! For now we will stick to custom build until Cantaloupe 6.0 release then.

_Offtop: an official docker image would be very neat 😄. Now we are using https://github.com/UCLALibrary/docker-cantaloupe, it can be fully configured with env variables, but docker image is not always up-to-date_

**Comment by adolski** [comment]
This is in place on `develop` now. There is an `HttpSource.BasicLookupStrategy.send_head_requests` config key, and `httpsource_resource_info()` may return a `send_head_request` key.

I will track the Docker image in #342.
