### ISSUE TITLE
tiles and scaleFactors information in manifest

### ISSUE THREAD

**Issue by jbarth-ubhd** [cantaloupe-project/cantaloupe#468]
Dear reader, I've found this example in the iiif docs:

![grafik](https://user-images.githubusercontent.com/30653779/116073744-1eac2900-a691-11eb-8286-b0a0c95835c7.png)
(cropped).

The `tiles[]` does not appear here https://heidicon.ub.uni-heidelberg.de/manifest/iiif/1139791/manifest.json in `canvases[1]` (tiff image with tiles and multiple scalefactors).

It seems to exist in the code here: https://github.com/cantaloupe-project/cantaloupe/blob/16e90feef6a848bbdbf9238f38fa8f28c4a4e532/src/main/java/edu/illinois/library/cantaloupe/resource/iiif/v2/ImageInfoFactory.java#L133

How do I get this information in our manifest?

Thanks, Jochen

**Comment by adolski** [comment]
Hi @jbarth-ubhd,

The link you posted is to an IIIF Presentation API manifest. I don't know how that is being generated on your end, but Cantaloupe doesn't have anything to do with the Presentation API. When I load the URL in `sequences[0].canvases[1].images[0].resource.service.@id` in that manifest, I see an IIIF Image API information response with `sizes` and `tiles` keys as expected.

**Comment by jbarth-ubhd** [comment]
@adolski: Thanks!
