### ISSUE TITLE
info.json: level2 => level0

### ISSUE THREAD

**Issue by bcail** [cantaloupe-project/cantaloupe#469]
I have a JP2 item - I requested the info.json, and it returned IIIF level2 info.json. I tried requesting the info.json again, and this time it changed to level0.

This is with cantaloupe 5.0.

**Comment by adolski** [comment]
I can't reproduce this.

**Comment by bcail** [comment]
Restarted cantaloupe - still level0.

Purged the caches & restarted cantaloupe - level2. Request again => back to level0.

**Comment by bcail** [comment]
In the level0 info.json, the "'formats': ['tif', 'jpg', 'gif', 'png']," part is dropped completely.

**Comment by adolski** [comment]
Thanks, that rings a bell. This is a bug in 5.0 that is fixed by 16e90feef6a848bbdbf9238f38fa8f28c4a4e532 for inclusion in 5.0.1.

**Comment by bcail** [comment]
Thanks.
