### ISSUE TITLE
Incorrect MIME type causes Nginx proxy with "X-Content-Type-Options: nosniff" to block static resources

### ISSUE THREAD

**Issue by jeau** [cantaloupe-project/cantaloupe#471]
I started to package Cantaloupe server as a new [Cloudron](https://www.cloudron.io/) application. Everything works fine with the single configuration file.

However, if I activate the optional administration web page, the static resources (css and js) don't load because of a `X-Content-Type-Options: nosniff` setting of Nginx proxy; I can't reasonably change this setting. This issue comes from an incorrect MIME type of this static resources served by Cantaloupe java server.

**Comment by adolski** [comment]
Thanks for reporting this, @jeau. The way that static assets are served changed in 5.0 and this was an oversight. It is now fixed on the `release/5.0` branch for inclusion in 5.0.1.
