### ISSUE TITLE
How max_pixels setting is expected to work? 

### ISSUE THREAD

**Issue by vchulski** [cantaloupe-project/cantaloupe#476]
Good day! 

I have a question regarding max_pixel setting for 5.0 version. 
I would like to use it to receive image of reduced size. So let's say my image is 20 megapixels - then I set this setting to 1 megapixel:
`max_pixels = 1048576`

And it works when I process local file. 
The question is - does it suppose to work with S3 as a source? 

When I tried it for S3 source it returns 403 - which doesn't seems to be correct and also it sends DEBUG message about AWS_REGION and AWS keys - which is incorrect, because when I restore original setting of max_pixel it works, but still sending this DEBUG message (screenshots attached)

First request with default max_pixels - receive result with 200 response, but DEBUG message shows that "unable to load credentials" 
![working_1_wrong_debug](https://user-images.githubusercontent.com/31348740/116988883-b20cdc00-acd9-11eb-940c-10a73da3be14.png)
![working_1](https://user-images.githubusercontent.com/31348740/116988882-b1744580-acd9-11eb-9650-b436a28b094c.png)

Second request error 403 (but the real thing is about pixels, right?) 
![non_working](https://user-images.githubusercontent.com/31348740/116988876-b0431880-acd9-11eb-9206-66c3d20de503.png)

**Comment by adolski** [comment]
Hi @vchulski,

The S3 client employs a "credentials provider chain" that asks each "credentials provider" in the chain [(see here for a list)](https://cantaloupe-project.github.io/manual/5.0/sources.html#S3Source) whether it can supply credentials, and any that can't will log a debug message like this, and then the chain will try the next one. When it finds one, it will log a message which you can see in your 2nd log excerpt: `Loading credentials from EnvironmentVariableCredentialsProvider()`. So, that is all normal and these messages are not related in any way to the setting of `max_pixels`.

What do you see in the log if you set `log_error_responses = true`?
