### ISSUE TITLE
Logo is missing

### ISSUE THREAD

**Issue by reny77** [cantaloupe-project/cantaloupe#477]
in version 5.0.1 I can't see the logo, in 5.0 it can be seen.

The logo is present in the jar.

**Comment by jeau** [comment]
in fact, it is the static assets that no longer load. I get Error 500 `Internal Server Error`.

**Comment by adolski** [comment]
Whoops, this is a bug that was introduced in cf5be9112ee7ea561c2229ddada7bb94317369c7 which was supposed to fix #471. It worked in my IDE at least. I will try to release a 5.0.2 some time today.

**Comment by jeau** [comment]
Thanks
