### ISSUE TITLE
OpenJpegProcessor trying to set lastModified time on source file

### ISSUE THREAD

**Issue by bcail** [cantaloupe-project/cantaloupe#478]
I'm using a FilesystemSource, with a jruby delegate to determine the path to the source file. It's working, but in the logs, I see the following error:
e.i.l.c.p.OpenJpegProcessor [OpenJpegProcessor.java:383] setSourceFile(): failed to touch file: <path to source file>

We have the source filesystem mounted read-only, so it fails. Is there a way to keep cantaloupe from trying to modify things in the source files? I'd rather cantaloupe not (try to) do anything to the source files, if possible.

**Comment by adolski** [comment]
Hi @bcail, are you using the source cache? See [here](https://github.com/cantaloupe-project/cantaloupe/blob/afc311ea42a512b86e90aefd53f93b79d93ee335/src/main/java/edu/illinois/library/cantaloupe/processor/OpenJpegProcessor.java#L376-L385) for an explanation of what is happening.

**Comment by bcail** [comment]
Nope, not using the source cache (if I understand it correctly):
processor.stream_retrieval_strategy = StreamStrategy
processor.fallback_retrieval_strategy = DownloadStrategy

And the JP2 wasn't added to the cache directory. The JP2 that it's trying to modify is the original, not a cached image.

Note: the original image file doesn't have a .jp2 extension, so I can see that it would need to create a symlink with the correct extension, but it seems like it should distinguish between files in the source cache, and files in a separate (non-cache) source directory.

**Comment by adolski** [comment]
Sorry, I get it now. I went and reduced the log level to debug. This is on all current branches now so will make it into 4.1.10 (if there is one) and 5.0.3.

**Comment by bcail** [comment]
Sorry - that commit looks like Cantaloupe will still be trying to update the last-modified timestamp on source images (it just won't write to the log as much if it fails). Is it documented anywhere that Cantaloupe is updating (or trying to update) that timestamp on all source images you expose to it? I would prefer for Cantaloupe to treat source images as read-only, but maybe no one else cares?

**Comment by adolski** [comment]
In theory OpenJpegProcessor doesn't need to set the last-modified time (`ctime`) here, only the last-accessed time (`atime`), but that may be disabled or impaired depending on the mount options, which is why it sets `ctime`. I guess there is an argument for setting `atime` instead and trusting the user to use the right mount options to not break the source cache if they are using it.

**Comment by bcail** [comment]
Are you talking about the source cache, or the filesystem source? I'm talking about the latter. They're different, aren't they? Or is the filesystem source supposed to be treated the same as the source cache?

If they're different, does cantaloupe have to modify the filesystem source image times, in order to make the source cache work?

**Comment by adolski** [comment]
The processor only sees the file, and doesn't know whether it's in the source cache or not. It doesn't understand the concept of a source cache. This code tries to modify the last-modified time based on the possibility that it might be.

The source cache uses last-accessed or last-modified times to determine validity. If the source cache weren't a factor then no timestamp-updating would be needed.

**Comment by bcail** [comment]
OK, thanks.
