### ISSUE TITLE
Failed to save the configuration with web admin page

### ISSUE THREAD

**Issue by jeau** [cantaloupe-project/cantaloupe#480]
I can't save the configuration via web admin page, same issue with Firefox and Chrome.

I get some errors like `Uncaught TypeError: data.delegateMethodInvocationCache is undefined`

**Comment by adolski** [comment]
I see the error related to `data.delegateMethodInvocationCache` in version 5.0.2, and I will push a commit shortly that fixes it. But I can't reproduce the config file failing to save.  Maybe a permissions issue?

**Comment by jeau** [comment]
@adolski your are right, it's a permission issue. I gave the group owner of configuration file write permission and it works now. Sorry.
