### ISSUE TITLE
undefined method `redactions' Latest cantaloupe 5.0.2 error

### ISSUE THREAD

**Issue by qudratullah1061** [cantaloupe-project/cantaloupe#483]
I have installed latest version of cantaloupe and getting these errors on console and log file.

1- NoMethodError: undefined method `metadata' for #<CustomDelegate:0x6e3e25ca>

2- javax.script.ScriptException: java.lang.NoSuchMethodException: (NoMethodError) undefined method `redactions' for #<CustomDelegate:0x258efd2c>

**Comment by adolski** [comment]
Are the `metadata` and `redactions` methods defined in your delegate script? If not, you will need to copy them over from the sample delegate script.

**Comment by qudratullah1061** [comment]
Thank you. Resolved.
