### ISSUE TITLE
Cantaloupe 5.0.2 redirection issue.

### ISSUE THREAD

**Issue by qudratullah1061** [cantaloupe-project/cantaloupe#484]
Hi,

I am using cantaloupe as my image server. When i am redirecting to low resolution image url if user request for full/full/0/defult.jpg  it is taking almost 2 seconds from delegates.rb script for redirection. I am using authorize and pre_authorize methods. Also pyramidal tile tiff image request is taking 2.x seconds to complete one request which is slow.

Also when there are multiple requests at a time images are delayed. I think cantaloupe is not utilizing server resources for processing. I am using amazon Large instance with 32 gb of Ram. Can you please tell me if i am missing any configuration so cantaloupe can use maximum resources?

Many thanks.  
Here is the screenshot.
![redirection](https://user-images.githubusercontent.com/32341027/117895395-b20f6c00-b2d7-11eb-81f2-2144d3df71c7.png)

**Comment by adolski** [comment]
The redirect from `pre_authorize()` or `authorize()` should be instantaneous. But if you are performing some kind of service call from within those methods that is taking 2 seconds, or if you are redirecting to an image that takes 2 seconds to load, then it could *seem* like the redirect is taking 2 seconds. That is my guess as to what's happening, which would make this a duplicate of #485.

**Comment by qudratullah1061** [comment]
Closing this. Will follow in ticket #485.
