### ISSUE TITLE
Image caching and content downloading.

### ISSUE THREAD

**Issue by qudratullah1061** [cantaloupe-project/cantaloupe#488]
Hi,

Images are not caching to client browser. If i hit same url multiple times every time request goes to server and downloads content each time. I think it should not download image every time if same request goes and can make server load less. What do you think? How can i achieve that?

Here are examples.
URL:
https://iiif.blavatnikarchive.org/iiif/2/baf__baf52574ad5d3093f4d995837db4e712ba08d23b90e4dd9ca34f1d9425346012/full/!1000,1000/0/default.jpg
Screenshot:
![downloadseverytime](https://user-images.githubusercontent.com/32341027/118497197-48abb500-b73e-11eb-9bdd-0268d6eb081b.png)

On the other hand you can have a look on IIIFHosting provider. They are caching and if same url hits from client browser they are serving from cache.
URL:
https://bafdigital.iiifhosting.com/iiif/bb42e63ff98e9c17f4a1e13cd37640416d7dd51c0cad49a0f4903bb7ac061e87/full/full/0/default.jpg
Screenshot:
![not downloads everytime](https://user-images.githubusercontent.com/32341027/118497449-86104280-b73e-11eb-9eef-d4f927cb347d.png)

Thanks.

**Comment by DiegoPino** [comment]
@qudratullah1061 hi. You probably have not configured https://cantaloupe-project.github.io/manual/4.1/caching.html#Client-Side%20Caching correctly. With that enabled and the right client settings I see the behavior (4.1.9) your are looking for. You may also test with the modes of operation (resolve first the source versus not) if you are doing appropriate measures for cache maintenance.

**Comment by qudratullah1061** [comment]
Hi,

I am using cantaloupe 5.0.2 and enabled client cache. Here are my settings.

cache.client.enabled = true

cache.client.max_age = 0
cache.client.shared_max_age =
cache.client.public = true
cache.client.private = false
cache.client.no_cache = false
cache.client.no_store = false
cache.client.must_revalidate = false
cache.client.proxy_revalidate = false
cache.client.no_transform = true

I am using s3 source but not working for me. Please let me know if you want any additional info.

Thanks.

**Comment by DiegoPino** [comment]
Cache-Control: max-age=0 is wrong for your use case. The client will cache the response but will fetch a new resource every time. Only case where max-age=0 will return (in your case) a local cache is if the IIIF server is down.

**Comment by DiegoPino** [comment]
@qudratullah1061 this page is a very good resource to understand client side caching
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

**Comment by qudratullah1061** [comment]
Thank you soo much. Resolved. :)
