### ISSUE TITLE
virtual reduced scale identifier reports full size of original in info.json

### ISSUE THREAD

**Issue by matthias-fratz-bsz** [cantaloupe-project/cantaloupe#500]
I am trying to restrict the resolutions that Cantaloupe delivers to unauthorized users. (For copyright reasons, we can only deliver at most 1000x1000 to external users.)

Using appropriate scale constraints (`;numerator:denominator` or `;1000:original-size` in my case) works fine as far as the image is concerned. However, the [info.json](https://github.com/cantaloupe-project/cantaloupe/files/6617630/info.json.txt) continues to report the size of the original image, 5088x3876. Consequently our viewer (openseadragon) tries to request tiles of an 5088x3876 image, eg. `http://localhost:8182/iiif/2/sgs_8b66e10d-5a7d-49f4-ae3a-b28142fe26bd;125:636/0,0,4096,3876/512,/0/default.jpg` and gets loads of HTTP 400s because that 4096x3876 size is of course way outside the reduced 1000x762 image.

Isn't Cantaloupe supposed to report the size of the reduced-scale version in info.json when the request is for a reduced-scale version? If not, is there any way to make it report the reduced sizes, short of overriding them in `extra_iiif2_information_response_keys`?

I am working with the 5.0.2 release JAR but a locally-built JAR of 6.0-SNAPSHOT as of 62f1bf842 shows exactly the same behavior.

**Comment by adolski** [comment]
Hi @matthias-fratz-bsz, thanks for reporting this. This is a silly bug introduced in 5.0 that is now fixed on the `release/5.0` branch, for inclusion in 5.0.3. There are also some new tests in place to prevent it from happening again.
