### ISSUE TITLE
pixelated image for virtual reduced scale identifiers and size other than "full"

### ISSUE THREAD

**Issue by matthias-fratz-bsz** [cantaloupe-project/cantaloupe#501]
Thanks for the extremely quick fix to #500! Unfortunately there seems to be an additional bug when combining the virtual reduced scale identifiers with a size specification that isn't `full`. In that situation Cantaloupe delivers an image that looks very pixelated.

- `http://localhost:8182/iiif/2/sgs_00000000001;25:507/full/full/0/default.png` ie. reduced-scale identifier + `full` yields the expected 200x136 pixel version of the source image
![full.png](https://user-images.githubusercontent.com/85570175/121325316-ca43cc80-c911-11eb-9c6e-3a5e9c4ac116.png)
- `http://localhost:8182/iiif/2/sgs_00000000001/full/200,/0/default.png` ie. normal identifier + a size specification yields the same image
- `http://localhost:8182/iiif/2/sgs_00000000001;25:507/full/200,/0/default.png` ie. reduced-scale identifier + a size specification yields a 200x136 image that obviously has 3x3 superpixels, as if it had been (nearest-neighbor) upscaled from an image 1/3 the size
![200,.png](https://user-images.githubusercontent.com/85570175/121325533-f9f2d480-c911-11eb-9e19-91f31eb19b58.png)

This behaves the same for the 5.0.2 release JAR, 5.0.3-SNAPSHOT as of 83aee2fbe and 6.0-SNAPSHOT as of 326106bc. That is, it doesn't seem to have been introduced with the fix for #500 (83aee2fbe). I am using the OpenJPEG processor, which Cantaloupe invokes as `opj_decompress -quiet -i /opt/expodev/cantaloupe/cache/sgs/kit/ten.jp2 -r 6 -o /opt/expodev/cantaloupe/OpenJpegProcessor-f8e03450-ea80-4636-b25e-fbd1df837cc0.bmp`. That `-r 6` is clearly excessive here, producing a 64x43 image. [Full log output of Cantaloupe 5.0.3](https://github.com/cantaloupe-project/cantaloupe/files/6622605/log.txt).

Curiously, `http://localhost:8182/iiif/2/sgs_00000000001;125:507/full/1000,/0/default.png` (ie. 5x the resolution of the problematic case) is also pixelated, but with 4x4 superpixels. The command in this case is `opj_decompress -quiet -i /opt/expodev/cantaloupe/cache/sgs/kit/ten.jp2 -r 4 -o /opt/expodev/cantaloupe/OpenJpegProcessor-d53b950e-af5e-43ea-b8ea-a03f053dd0c8.bmp`, where `-r 4` again reduces resolution too much. Normal identifiers (`http://localhost:8182/iiif/2/sgs_00000000001/full/full/0/default.jpg`) with `full` simply yields the 4056x2764 source image.

Please let me know if you need further information. In particular I can provide both the JPEG2000 source image (it's public domain this time) and any derivatives if necessary.

**Comment by adolski** [comment]
This is another bug, @matthias-fratz-bsz, but one that affects only OpenJpegProcessor. It should be fixed now; let me know if you notice otherwise.
