### ISSUE TITLE
Feature request: add proxy support for HttpSource  OkHttp Client

### ISSUE THREAD

**Issue by mightymax** [cantaloupe-project/cantaloupe#502]
It would be nice to have support for HTTP proxies when using HttpSource with the new OkHttp client (introduced in Cantaloupe 5). Sometimes the target server (Nuxeo in my case) can only be accessed through a HTTP proxy. I've managed to introduce this feature , see Pull Request #499.

**Comment by adolski** [comment]
Thanks @mightymax , I'll try to take a look at this soon.
