### ISSUE TITLE
Extra v in the name of the JAR file in the example of run command

### ISSUE THREAD

**Issue by daliboris** [cantaloupe-project/cantaloupe#518]
On the [get started](https://cantaloupe-project.github.io) page an example for runnig Cantaloupe from the commnad line contanins `v` before version number (eg. `cantaloupe-v5.0.3.`), but the distributed file (at least for Windows version) doesn't contain this letter, ie. `cantaloupe-5.0.3.jar`.

**Comment by adolski** [comment]
Thanks for pointing this out, @daliboris. It's fixed now.
