### ISSUE TITLE
Feature Request: purge file from source cache if corrupt

### ISSUE THREAD

**Issue by PCOWandre** [cantaloupe-project/cantaloupe#529]
We've hit an interesting corner-case where sometimes the upstream http service is returning corrupt images -- namely, it manages to return a 200 with a stack trace in it. This is obviously a horrible bug in the upstream.

However, because it is returned with a 200 cantaloupe stores this in the source cache. Then all subsequent requests for this file fail with quite reasonable messages about it not being in a format that can be handled. This is all very reasonable.

Feature-wise, I think it would be excellent if cantaloupe could evict a file from the source cache if it was deemed to be corrupt or otherwise non-useful. This would happen after a failed transaction so it shouldn't add too much CPU or I/O cost to implement.

**Comment by adolski** [comment]
Hi @PCOWandre, thanks for reporting this unusual case. This feature is now on 6.0-SNAPSHOT (`develop` branch). To be conservative, I've left it disabled for the time being, but I can't really think of a reason not to enable it. I would be interested to hear some opinions on this. At some point I may just remove that config key and leave it enabled.

**Comment by PCOWandre** [comment]
Thanks for your prompt response! We'll look at getting the current code into our staging environment as soon as possible to participate in testing.
