### ISSUE TITLE
Question: What is wrong with my configuration?

### ISSUE THREAD

**Issue by busymo** [cantaloupe-project/cantaloupe#531]
I have cantaloupe configured with docker, based on https://github.com/LvanWissen/docker-cantaloupe, and my path prefix is:  FILESYSTEMSOURCE_BASICLOOKUPSTRATEGY_PATH_PREFIX="/opt/basel_papyri/backend/images/" 

I am running cantaloupe in nginx as a proxy and when I check its index route, I can access Cantaloupe Image Server (version). But when I try to access the images:
https://<server_name>/cantaloupe/iiif/3/1/images/<image_name.jpg>/info.json
I get the message that there exists no route about it?

Has anybody configured cantaloupe in ubuntu using nginx? Thanks in advance

**Comment by DiegoPino** [comment]
@busymo there may be a few things that you may check but first, your path seem to be incorrect. There is no V3 endpoint and the extra 1/images/ are not clear to me why

There are higher chances that the default for you is:

https://<server_name>/cantaloupe/iiif/2/<image_name.jpg>/info.json

Also, in our case with ngnix this server config resolves well (we do have some smaller proxy buffer issues but that is totally a different topic): cantaloupe as an upstream and passing some important HEADERS that cantaloupe will need 

https://github.com/esmero/archipelago-deployment-live/blob/1.0.0-RC3/config_storage/nginxconfig/conf.d/nginx.conf#L1-L31

**Comment by busymo** [comment]
@DiegoPino, thanks for your comment. The reason why I added the 1/images/image_name is that I have the images there so in subfolder + image name.

**Comment by DiegoPino** [comment]
@busymo ok! If that is the case then you need to URL encode your folders. The extra / are not being passed to cantaloupe as part of the Identifier, but to ngnix as paths it needs to resolve. In other words, the ID (including your folders) need to be single URL encoded string.  See https://cantaloupe-project.github.io/manual/5.0/sources.html#FilesystemSource or the DOCS for the version you are running (still iiif/3 is not right)!

**Comment by busymo** [comment]
Okay, I understood. But what if I just place the images in the /opt/images/ and I have the following configuration for the cantaloupe, I still can not get the info.json part from the image. An example of an image name consists of "1.RectoIliad19thTbook-IR-enh.jpg" (so dots and lines are part of the name which in this case will be acting as an id). 

Why is it still the case that I do not get the images? Cantaloupe is running in http://127.0.0.1:8182 and it is proxied in https://servername/cantaloupe

<img width="497" alt="Screenshot 2021-08-29 at 10 21 27" src="https://user-images.githubusercontent.com/56075989/131243756-ee152d93-a38e-40cb-95ff-f27d8e01b359.png">
