### ISSUE TITLE
Images start deleting after specific interval. Cantaloupe 5.0.2

### ISSUE THREAD

**Issue by qudratullah1061** [cantaloupe-project/cantaloupe#532]
Hi,
				
Thank you Cantaloupe team for your support in managing this product. I came here with a question. I have setup Cantaloupe and facing an issue.
I am using version v5.0.2, Configured successfully, I have assets(pyramidal tiff) on the amazon server under bucket Bucket-ABC.
Under that bucket, I have 3 inner folders in which I have images for different clients. Hierarchy is
Bucket-ABC/A
Bucket-ABC/B
Bucket-ABC/C
Also, I have enabled derivative and server cache. Cache stored on Bucket-ABC/cache folder on amazon.

![cantaloupe](https://user-images.githubusercontent.com/32341027/131359583-d5fdfb3d-5789-481b-870c-02565d23a035.png)

				
The problem is my processed images (pyramidal tiff) start deleting after a specific interval, last time on 27/07/2021.
We tried to detect the issue of how images can be deleted automatically, but no luck.
Now exactly after 30 days images start deleted again on 27/08/2021. We shut down our cantaloupe server and images stopped deleting.
After some time when we restart the server images start deleting again which means some auto script running with time intervals. After that, we changed settings in the "Derivative Cache Time-To-Live" value to zero (0), uncheck purge missing and source images stopped deleting.

![derivate cache cantaloupe](https://user-images.githubusercontent.com/32341027/131359726-83d020bd-ba60-4d28-8e16-9a88ef0597ea.png)

				
I want to confirm is there anything that I have misconfigured? Or is this a bug that the server starts deleting original images files with cache files as these both are in same bucket?

Please guide.
				
Many thanks.

**Comment by adolski** [comment]
It looks like you've found a bug whereby S3Cache is not respecting the key prefix (`S3Cache.object_key_prefix`) when purging all or invalid content. There is a fix now on the `release/5.0` branch which will be included in 5.0.4.

In the meantime, this can be worked around either by setting the TTL to 0 (as you've done), or giving S3Cache its own bucket.

**Comment by qudratullah1061** [comment]
Thank you @adolski for your guidance regarding this issue. We were in trouble and have lost our original media files twice which were around 0.2 million. At least now we know what actually happened.
