### ISSUE TITLE
The requested pixel area exceeds the maximum threshold (max_pixels) set in the configuration.

### ISSUE THREAD

**Issue by marlara** [cantaloupe-project/cantaloupe#537]
Hi,
I have Cantaloupe version 5.0.3. I get this message when I try to access an IIIF image. I've seen that this issue should be already resolved with Cantaloupe 5.0. Is it possible there are some problems by my side?

The IIIF giving the problem is: https://mostra1972.unipr.it:8183/iiif/2/D000533_1S_AlbiniW_ST42.tif/full/full/0/default.jpg

**Comment by giancarlobi** [comment]
@marlara according this thread https://gitmemory.cn/repo/cantaloupe-project/cantaloupe/issues/426 if you use .../full/max/... it works https://mostra1972.unipr.it:8183/iiif/2/D000533_1S_AlbiniW_ST42.tif/full/max/0/default.jpg
Not sure if this help you and I'm not so skilled with Cantaloupe but I was interested by another Italian institution working with Cantaloupe.

**Comment by marlara** [comment]
Thank you @giancarlobi! This is really useful. I saw the thread, but didn't catch the solution. If you're interested you could write me anytime lara.marzi[at]gmail
