### ISSUE TITLE
patches for v5

### ISSUE THREAD

**Issue by mrghosti3** [cantaloupe-project/cantaloupe#623]
Hi @adolski,
I would like to port over some changes made by [La0](https://github.com/La0): #550 and #548. The changes I'm working will added [here](https://github.com/mrghosti3/cantaloupe/tree/patch/5.0.6) which is based on this repos [release/5.0](https://github.com/cantaloupe-project/cantaloupe/tree/release/5.0) branch.

Related pull requests: #549 #551

**Comment by janhoy** [comment]
What's the status on this @mrghosti3 ?

**Comment by mrghosti3** [comment]
Backported both PRs (#549 and #551) for the v5.0.6 patch. Just waiting for any comments/suggestions to the commits. Other than that, I can create a PR.

**Comment by mrghosti3** [comment]
Could use some advice whether my approach of back-porting is acceptable.

**Comment by mrghosti3** [comment]
Closing this as work for this project is renewed.
