### ISSUE TITLE
Develop branch missing commits from version 5.0.6

### ISSUE THREAD

**Issue by VonUniGE** [cantaloupe-project/cantaloupe#667]
### Issue Description:

It appears that the develop branch does not contain the commits that were used in the 5.0.6 release. 

To ensure consistency and proper workflow, the release/5.0 branch should be merged into the develop branch. This process should be similar to the merge performed in commit efed8c201.

### Steps to Reproduce:

1. Check the commit history of the develop branch.
2. Check the commit history of the release/5.0 branch.
3. Compare the commits used in version 5.0.6 and those present in the develop branch.

### Expected Result:

The develop branch should contain all commits from the release/5.0 branch, including those used in version 5.0.6.

### Suggested Solution:

Merge the release/5.0 branch into the develop branch, as was done in commit efed8c201.

**Comment by glenrobson** [comment]
Hi @VonUniGE we are discussing this in the Cantaloupe developer meetings. It would be great if you could join. The notes are here:

https://docs.google.com/document/d/1jovu17P1nKxAUiG5kyxy10qUa4URmJNmBKz9LGirbAw/edit

**Comment by VonUniGE** [comment]
Hi @glenrobson, Thank you for the invitation, but I was not available at that time.

**Comment by glenrobson** [comment]
Completed in #668
